# komle/write_bindings/_gml.py
# -*- coding: utf-8 -*-
# PyXB bindings for NM:c4f74fce23a2f49d6da683416eb2980bfced7e33
# Generated 2020-04-28 14:15:45.263184 by PyXB version 1.2.6 using Python 3.7.5.final.0
# Namespace http://www.opengis.net/gml/3.2 [xmlns:gml]

from __future__ import unicode_literals
import pyxb
import pyxb.binding
import pyxb.binding.saxer
import io
import pyxb.utils.utility
import pyxb.utils.domutils
import sys
import pyxb.utils.six as _six
# Unique identifier for bindings created at the same time
_GenerationUID = pyxb.utils.utility.UniqueIdentifier('urn:uuid:12a7727e-8949-11ea-9269-e1ea09be6e55')

# Version of PyXB used to generate the bindings
_PyXBVersion = '1.2.6'
# Generated bindings are not compatible across PyXB versions
if pyxb.__version__ != _PyXBVersion:
    raise pyxb.PyXBVersionError(_PyXBVersion)

# A holder for module-level binding classes so we can access them from
# inside class definitions where property names may conflict.
_module_typeBindings = pyxb.utils.utility.Object()

# Import bindings for namespaces imported into schema
import komle.write_bindings._nsgroup as _ImportedBinding_write_bindings__nsgroup

# NOTE: All namespace declarations are reserved within the binding
Namespace = pyxb.namespace.NamespaceForURI('http://www.opengis.net/gml/3.2', create_if_missing=True)
Namespace.configureCategories(['typeBinding', 'elementBinding'])

def CreateFromDocument (xml_text, default_namespace=None, location_base=None):
    """Parse the given XML and use the document element to create a
    Python instance.

    @param xml_text An XML document.  This should be data (Python 2
    str or Python 3 bytes), or a text (Python 2 unicode or Python 3
    str) in the L{pyxb._InputEncoding} encoding.

    @keyword default_namespace The L{pyxb.Namespace} instance to use as the
    default namespace where there is no default namespace in scope.
    If unspecified or C{None}, the namespace of the module containing
    this function will be used.

    @keyword location_base: An object to be recorded as the base of all
    L{pyxb.utils.utility.Location} instances associated with events and
    objects handled by the parser.  You might pass the URI from which
    the document was obtained.
    """

    if pyxb.XMLStyle_saxer != pyxb._XMLStyle:
        dom = pyxb.utils.domutils.StringToDOM(xml_text)
        return CreateFromDOM(dom.documentElement, default_namespace=default_namespace)
    if default_namespace is None:
        default_namespace = Namespace.fallbackNamespace()
    saxer = pyxb.binding.saxer.make_parser(fallback_namespace=default_namespace, location_base=location_base)
    handler = saxer.getContentHandler()
    xmld = xml_text
    if isinstance(xmld, _six.text_type):
        xmld = xmld.encode(pyxb._InputEncoding)
    saxer.parse(io.BytesIO(xmld))
    instance = handler.rootObject()
    return instance

def CreateFromDOM (node, default_namespace=None):
    """Create a Python instance from the given DOM node.
    The node tag must correspond to an element declaration in this module.

    @deprecated: Forcing use of DOM interface is unnecessary; use L{CreateFromDocument}."""
    if default_namespace is None:
        default_namespace = Namespace.fallbackNamespace()
    return pyxb.binding.basis.element.AnyCreateFromDOM(node, default_namespace)

from komle.write_bindings._nsgroup import operationVersion # {http://www.opengis.net/gml/3.2}operationVersion
from komle.write_bindings._nsgroup import modifiedCoordinate # {http://www.opengis.net/gml/3.2}modifiedCoordinate
from komle.write_bindings._nsgroup import stringValue # {http://www.opengis.net/gml/3.2}stringValue
from komle.write_bindings._nsgroup import integerValue # {http://www.opengis.net/gml/3.2}integerValue
from komle.write_bindings._nsgroup import booleanValue # {http://www.opengis.net/gml/3.2}booleanValue
from komle.write_bindings._nsgroup import valueFile # {http://www.opengis.net/gml/3.2}valueFile
from komle.write_bindings._nsgroup import sourceDimensions # {http://www.opengis.net/gml/3.2}sourceDimensions
from komle.write_bindings._nsgroup import targetDimensions # {http://www.opengis.net/gml/3.2}targetDimensions
from komle.write_bindings._nsgroup import minimumOccurs # {http://www.opengis.net/gml/3.2}minimumOccurs
from komle.write_bindings._nsgroup import maximumOccurs # {http://www.opengis.net/gml/3.2}maximumOccurs
from komle.write_bindings._nsgroup import minimumValue # {http://www.opengis.net/gml/3.2}minimumValue
from komle.write_bindings._nsgroup import maximumValue # {http://www.opengis.net/gml/3.2}maximumValue
from komle.write_bindings._nsgroup import realizationEpoch # {http://www.opengis.net/gml/3.2}realizationEpoch
from komle.write_bindings._nsgroup import origin # {http://www.opengis.net/gml/3.2}origin
from komle.write_bindings._nsgroup import remarks # {http://www.opengis.net/gml/3.2}remarks
from komle.write_bindings._nsgroup import AbstractObject # {http://www.opengis.net/gml/3.2}AbstractObject
from komle.write_bindings._nsgroup import reversePropertyName # {http://www.opengis.net/gml/3.2}reversePropertyName
from komle.write_bindings._nsgroup import targetElement # {http://www.opengis.net/gml/3.2}targetElement
from komle.write_bindings._nsgroup import associationName # {http://www.opengis.net/gml/3.2}associationName
from komle.write_bindings._nsgroup import defaultCodeSpace # {http://www.opengis.net/gml/3.2}defaultCodeSpace
from komle.write_bindings._nsgroup import gmlProfileSchema # {http://www.opengis.net/gml/3.2}gmlProfileSchema
from komle.write_bindings._nsgroup import scope # {http://www.opengis.net/gml/3.2}scope
from komle.write_bindings._nsgroup import duration # {http://www.opengis.net/gml/3.2}duration
from komle.write_bindings._nsgroup import AbstractValue # {http://www.opengis.net/gml/3.2}AbstractValue
from komle.write_bindings._nsgroup import AbstractScalarValue # {http://www.opengis.net/gml/3.2}AbstractScalarValue
from komle.write_bindings._nsgroup import AbstractScalarValueList # {http://www.opengis.net/gml/3.2}AbstractScalarValueList
from komle.write_bindings._nsgroup import parameterValue # {http://www.opengis.net/gml/3.2}parameterValue
from komle.write_bindings._nsgroup import AbstractGeneralParameterValue # {http://www.opengis.net/gml/3.2}AbstractGeneralParameterValue
from komle.write_bindings._nsgroup import integerValueList # {http://www.opengis.net/gml/3.2}integerValueList
from komle.write_bindings._nsgroup import formula # {http://www.opengis.net/gml/3.2}formula
from komle.write_bindings._nsgroup import axisAbbrev # {http://www.opengis.net/gml/3.2}axisAbbrev
from komle.write_bindings._nsgroup import rangeSet # {http://www.opengis.net/gml/3.2}rangeSet
from komle.write_bindings._nsgroup import DataBlock # {http://www.opengis.net/gml/3.2}DataBlock
from komle.write_bindings._nsgroup import tupleList # {http://www.opengis.net/gml/3.2}tupleList
from komle.write_bindings._nsgroup import File # {http://www.opengis.net/gml/3.2}File
from komle.write_bindings._nsgroup import coverageFunction # {http://www.opengis.net/gml/3.2}coverageFunction
from komle.write_bindings._nsgroup import CoverageMappingRule # {http://www.opengis.net/gml/3.2}CoverageMappingRule
from komle.write_bindings._nsgroup import GridFunction # {http://www.opengis.net/gml/3.2}GridFunction
from komle.write_bindings._nsgroup import anchorDefinition # {http://www.opengis.net/gml/3.2}anchorDefinition
from komle.write_bindings._nsgroup import secondDefiningParameter # {http://www.opengis.net/gml/3.2}secondDefiningParameter
from komle.write_bindings._nsgroup import SecondDefiningParameter # {http://www.opengis.net/gml/3.2}SecondDefiningParameter
from komle.write_bindings._nsgroup import anchorPoint # {http://www.opengis.net/gml/3.2}anchorPoint
from komle.write_bindings._nsgroup import usesValue # {http://www.opengis.net/gml/3.2}usesValue
from komle.write_bindings._nsgroup import dmsAngleValue # {http://www.opengis.net/gml/3.2}dmsAngleValue
from komle.write_bindings._nsgroup import includesValue # {http://www.opengis.net/gml/3.2}includesValue
from komle.write_bindings._nsgroup import methodFormula # {http://www.opengis.net/gml/3.2}methodFormula
from komle.write_bindings._nsgroup import dmsAngle # {http://www.opengis.net/gml/3.2}dmsAngle
from komle.write_bindings._nsgroup import decimalMinutes # {http://www.opengis.net/gml/3.2}decimalMinutes
from komle.write_bindings._nsgroup import minutes # {http://www.opengis.net/gml/3.2}minutes
from komle.write_bindings._nsgroup import seconds # {http://www.opengis.net/gml/3.2}seconds
from komle.write_bindings._nsgroup import members # {http://www.opengis.net/gml/3.2}members
from komle.write_bindings._nsgroup import AbstractMetaData # {http://www.opengis.net/gml/3.2}AbstractMetaData
from komle.write_bindings._nsgroup import coordinates # {http://www.opengis.net/gml/3.2}coordinates
from komle.write_bindings._nsgroup import LocationKeyWord # {http://www.opengis.net/gml/3.2}LocationKeyWord
from komle.write_bindings._nsgroup import featureMembers # {http://www.opengis.net/gml/3.2}featureMembers
from komle.write_bindings._nsgroup import track # {http://www.opengis.net/gml/3.2}track
from komle.write_bindings._nsgroup import indirectEntry # {http://www.opengis.net/gml/3.2}indirectEntry
from komle.write_bindings._nsgroup import polygonPatches # {http://www.opengis.net/gml/3.2}polygonPatches
from komle.write_bindings._nsgroup import trianglePatches # {http://www.opengis.net/gml/3.2}trianglePatches
from komle.write_bindings._nsgroup import pointArrayProperty # {http://www.opengis.net/gml/3.2}pointArrayProperty
from komle.write_bindings._nsgroup import curveArrayProperty # {http://www.opengis.net/gml/3.2}curveArrayProperty
from komle.write_bindings._nsgroup import surfaceArrayProperty # {http://www.opengis.net/gml/3.2}surfaceArrayProperty
from komle.write_bindings._nsgroup import solidArrayProperty # {http://www.opengis.net/gml/3.2}solidArrayProperty
from komle.write_bindings._nsgroup import history # {http://www.opengis.net/gml/3.2}history
from komle.write_bindings._nsgroup import locationName # {http://www.opengis.net/gml/3.2}locationName
from komle.write_bindings._nsgroup import geometryMembers # {http://www.opengis.net/gml/3.2}geometryMembers
from komle.write_bindings._nsgroup import pointMembers # {http://www.opengis.net/gml/3.2}pointMembers
from komle.write_bindings._nsgroup import curveMembers # {http://www.opengis.net/gml/3.2}curveMembers
from komle.write_bindings._nsgroup import surfaceMembers # {http://www.opengis.net/gml/3.2}surfaceMembers
from komle.write_bindings._nsgroup import solidMembers # {http://www.opengis.net/gml/3.2}solidMembers
from komle.write_bindings._nsgroup import exterior # {http://www.opengis.net/gml/3.2}exterior
from komle.write_bindings._nsgroup import interior # {http://www.opengis.net/gml/3.2}interior
from komle.write_bindings._nsgroup import AbstractCurveSegment # {http://www.opengis.net/gml/3.2}AbstractCurveSegment
from komle.write_bindings._nsgroup import segments # {http://www.opengis.net/gml/3.2}segments
from komle.write_bindings._nsgroup import AffinePlacement # {http://www.opengis.net/gml/3.2}AffinePlacement
from komle.write_bindings._nsgroup import AbstractSurfacePatch # {http://www.opengis.net/gml/3.2}AbstractSurfacePatch
from komle.write_bindings._nsgroup import patches # {http://www.opengis.net/gml/3.2}patches
from komle.write_bindings._nsgroup import AbstractGML # {http://www.opengis.net/gml/3.2}AbstractGML
from komle.write_bindings._nsgroup import abstractInlineProperty # {http://www.opengis.net/gml/3.2}abstractInlineProperty
from komle.write_bindings._nsgroup import name # {http://www.opengis.net/gml/3.2}name
from komle.write_bindings._nsgroup import topoPointProperty # {http://www.opengis.net/gml/3.2}topoPointProperty
from komle.write_bindings._nsgroup import topoCurveProperty # {http://www.opengis.net/gml/3.2}topoCurveProperty
from komle.write_bindings._nsgroup import topoSurfaceProperty # {http://www.opengis.net/gml/3.2}topoSurfaceProperty
from komle.write_bindings._nsgroup import topoVolumeProperty # {http://www.opengis.net/gml/3.2}topoVolumeProperty
from komle.write_bindings._nsgroup import topoPrimitiveMembers # {http://www.opengis.net/gml/3.2}topoPrimitiveMembers
from komle.write_bindings._nsgroup import catalogSymbol # {http://www.opengis.net/gml/3.2}catalogSymbol
from komle.write_bindings._nsgroup import valueComponents # {http://www.opengis.net/gml/3.2}valueComponents
from komle.write_bindings._nsgroup import ParameterValue # {http://www.opengis.net/gml/3.2}ParameterValue
from komle.write_bindings._nsgroup import ParameterValueGroup # {http://www.opengis.net/gml/3.2}ParameterValueGroup
from komle.write_bindings._nsgroup import derivedCRSType # {http://www.opengis.net/gml/3.2}derivedCRSType
from komle.write_bindings._nsgroup import axisDirection # {http://www.opengis.net/gml/3.2}axisDirection
from komle.write_bindings._nsgroup import rangeMeaning # {http://www.opengis.net/gml/3.2}rangeMeaning
from komle.write_bindings._nsgroup import pixelInCell # {http://www.opengis.net/gml/3.2}pixelInCell
from komle.write_bindings._nsgroup import Null # {http://www.opengis.net/gml/3.2}Null
from komle.write_bindings._nsgroup import degrees # {http://www.opengis.net/gml/3.2}degrees
from komle.write_bindings._nsgroup import Bag # {http://www.opengis.net/gml/3.2}Bag
from komle.write_bindings._nsgroup import Array # {http://www.opengis.net/gml/3.2}Array
from komle.write_bindings._nsgroup import GenericMetaData # {http://www.opengis.net/gml/3.2}GenericMetaData
from komle.write_bindings._nsgroup import AbstractTimeSlice # {http://www.opengis.net/gml/3.2}AbstractTimeSlice
from komle.write_bindings._nsgroup import AbstractFeature # {http://www.opengis.net/gml/3.2}AbstractFeature
from komle.write_bindings._nsgroup import AbstractGeometry # {http://www.opengis.net/gml/3.2}AbstractGeometry
from komle.write_bindings._nsgroup import pos # {http://www.opengis.net/gml/3.2}pos
from komle.write_bindings._nsgroup import posList # {http://www.opengis.net/gml/3.2}posList
from komle.write_bindings._nsgroup import Envelope # {http://www.opengis.net/gml/3.2}Envelope
from komle.write_bindings._nsgroup import LineStringSegment # {http://www.opengis.net/gml/3.2}LineStringSegment
from komle.write_bindings._nsgroup import ArcString # {http://www.opengis.net/gml/3.2}ArcString
from komle.write_bindings._nsgroup import ArcStringByBulge # {http://www.opengis.net/gml/3.2}ArcStringByBulge
from komle.write_bindings._nsgroup import ArcByCenterPoint # {http://www.opengis.net/gml/3.2}ArcByCenterPoint
from komle.write_bindings._nsgroup import CubicSpline # {http://www.opengis.net/gml/3.2}CubicSpline
from komle.write_bindings._nsgroup import BSpline # {http://www.opengis.net/gml/3.2}BSpline
from komle.write_bindings._nsgroup import OffsetCurve # {http://www.opengis.net/gml/3.2}OffsetCurve
from komle.write_bindings._nsgroup import Clothoid # {http://www.opengis.net/gml/3.2}Clothoid
from komle.write_bindings._nsgroup import GeodesicString # {http://www.opengis.net/gml/3.2}GeodesicString
from komle.write_bindings._nsgroup import PolygonPatch # {http://www.opengis.net/gml/3.2}PolygonPatch
from komle.write_bindings._nsgroup import Triangle # {http://www.opengis.net/gml/3.2}Triangle
from komle.write_bindings._nsgroup import Rectangle # {http://www.opengis.net/gml/3.2}Rectangle
from komle.write_bindings._nsgroup import AbstractParametricCurveSurface # {http://www.opengis.net/gml/3.2}AbstractParametricCurveSurface
from komle.write_bindings._nsgroup import identifier # {http://www.opengis.net/gml/3.2}identifier
from komle.write_bindings._nsgroup import AbstractImplicitGeometry # {http://www.opengis.net/gml/3.2}AbstractImplicitGeometry
from komle.write_bindings._nsgroup import AbstractTimeObject # {http://www.opengis.net/gml/3.2}AbstractTimeObject
from komle.write_bindings._nsgroup import timePosition # {http://www.opengis.net/gml/3.2}timePosition
from komle.write_bindings._nsgroup import AbstractTopology # {http://www.opengis.net/gml/3.2}AbstractTopology
from komle.write_bindings._nsgroup import CompositeValue # {http://www.opengis.net/gml/3.2}CompositeValue
from komle.write_bindings._nsgroup import coordinateOperationAccuracy # {http://www.opengis.net/gml/3.2}coordinateOperationAccuracy
from komle.write_bindings._nsgroup import sourceCRS # {http://www.opengis.net/gml/3.2}sourceCRS
from komle.write_bindings._nsgroup import targetCRS # {http://www.opengis.net/gml/3.2}targetCRS
from komle.write_bindings._nsgroup import coordOperation # {http://www.opengis.net/gml/3.2}coordOperation
from komle.write_bindings._nsgroup import method # {http://www.opengis.net/gml/3.2}method
from komle.write_bindings._nsgroup import value # {http://www.opengis.net/gml/3.2}value
from komle.write_bindings._nsgroup import valueList # {http://www.opengis.net/gml/3.2}valueList
from komle.write_bindings._nsgroup import operationParameter # {http://www.opengis.net/gml/3.2}operationParameter
from komle.write_bindings._nsgroup import group # {http://www.opengis.net/gml/3.2}group
from komle.write_bindings._nsgroup import formulaCitation # {http://www.opengis.net/gml/3.2}formulaCitation
from komle.write_bindings._nsgroup import parameter # {http://www.opengis.net/gml/3.2}parameter
from komle.write_bindings._nsgroup import conversion # {http://www.opengis.net/gml/3.2}conversion
from komle.write_bindings._nsgroup import componentReferenceSystem # {http://www.opengis.net/gml/3.2}componentReferenceSystem
from komle.write_bindings._nsgroup import ellipsoidalCS # {http://www.opengis.net/gml/3.2}ellipsoidalCS
from komle.write_bindings._nsgroup import cartesianCS # {http://www.opengis.net/gml/3.2}cartesianCS
from komle.write_bindings._nsgroup import sphericalCS # {http://www.opengis.net/gml/3.2}sphericalCS
from komle.write_bindings._nsgroup import geodeticDatum # {http://www.opengis.net/gml/3.2}geodeticDatum
from komle.write_bindings._nsgroup import verticalCS # {http://www.opengis.net/gml/3.2}verticalCS
from komle.write_bindings._nsgroup import verticalDatum # {http://www.opengis.net/gml/3.2}verticalDatum
from komle.write_bindings._nsgroup import baseGeodeticCRS # {http://www.opengis.net/gml/3.2}baseGeodeticCRS
from komle.write_bindings._nsgroup import baseCRS # {http://www.opengis.net/gml/3.2}baseCRS
from komle.write_bindings._nsgroup import coordinateSystem # {http://www.opengis.net/gml/3.2}coordinateSystem
from komle.write_bindings._nsgroup import cylindricalCS # {http://www.opengis.net/gml/3.2}cylindricalCS
from komle.write_bindings._nsgroup import linearCS # {http://www.opengis.net/gml/3.2}linearCS
from komle.write_bindings._nsgroup import polarCS # {http://www.opengis.net/gml/3.2}polarCS
from komle.write_bindings._nsgroup import userDefinedCS # {http://www.opengis.net/gml/3.2}userDefinedCS
from komle.write_bindings._nsgroup import engineeringDatum # {http://www.opengis.net/gml/3.2}engineeringDatum
from komle.write_bindings._nsgroup import affineCS # {http://www.opengis.net/gml/3.2}affineCS
from komle.write_bindings._nsgroup import imageDatum # {http://www.opengis.net/gml/3.2}imageDatum
from komle.write_bindings._nsgroup import timeCS # {http://www.opengis.net/gml/3.2}timeCS
from komle.write_bindings._nsgroup import temporalDatum # {http://www.opengis.net/gml/3.2}temporalDatum
from komle.write_bindings._nsgroup import axis # {http://www.opengis.net/gml/3.2}axis
from komle.write_bindings._nsgroup import AbstractCoverage # {http://www.opengis.net/gml/3.2}AbstractCoverage
from komle.write_bindings._nsgroup import domainSet # {http://www.opengis.net/gml/3.2}domainSet
from komle.write_bindings._nsgroup import rangeParameters # {http://www.opengis.net/gml/3.2}rangeParameters
from komle.write_bindings._nsgroup import doubleOrNilReasonTupleList # {http://www.opengis.net/gml/3.2}doubleOrNilReasonTupleList
from komle.write_bindings._nsgroup import primeMeridian # {http://www.opengis.net/gml/3.2}primeMeridian
from komle.write_bindings._nsgroup import ellipsoid # {http://www.opengis.net/gml/3.2}ellipsoid
from komle.write_bindings._nsgroup import semiMajorAxis # {http://www.opengis.net/gml/3.2}semiMajorAxis
from komle.write_bindings._nsgroup import datumRef # {http://www.opengis.net/gml/3.2}datumRef
from komle.write_bindings._nsgroup import usesPrimeMeridian # {http://www.opengis.net/gml/3.2}usesPrimeMeridian
from komle.write_bindings._nsgroup import usesEllipsoid # {http://www.opengis.net/gml/3.2}usesEllipsoid
from komle.write_bindings._nsgroup import geodeticDatumRef # {http://www.opengis.net/gml/3.2}geodeticDatumRef
from komle.write_bindings._nsgroup import ellipsoidRef # {http://www.opengis.net/gml/3.2}ellipsoidRef
from komle.write_bindings._nsgroup import primeMeridianRef # {http://www.opengis.net/gml/3.2}primeMeridianRef
from komle.write_bindings._nsgroup import engineeringDatumRef # {http://www.opengis.net/gml/3.2}engineeringDatumRef
from komle.write_bindings._nsgroup import imageDatumRef # {http://www.opengis.net/gml/3.2}imageDatumRef
from komle.write_bindings._nsgroup import verticalDatumRef # {http://www.opengis.net/gml/3.2}verticalDatumRef
from komle.write_bindings._nsgroup import temporalDatumRef # {http://www.opengis.net/gml/3.2}temporalDatumRef
from komle.write_bindings._nsgroup import coordinateOperationRef # {http://www.opengis.net/gml/3.2}coordinateOperationRef
from komle.write_bindings._nsgroup import singleOperationRef # {http://www.opengis.net/gml/3.2}singleOperationRef
from komle.write_bindings._nsgroup import operationRef # {http://www.opengis.net/gml/3.2}operationRef
from komle.write_bindings._nsgroup import generalConversionRef # {http://www.opengis.net/gml/3.2}generalConversionRef
from komle.write_bindings._nsgroup import generalTransformationRef # {http://www.opengis.net/gml/3.2}generalTransformationRef
from komle.write_bindings._nsgroup import usesSingleOperation # {http://www.opengis.net/gml/3.2}usesSingleOperation
from komle.write_bindings._nsgroup import concatenatedOperationRef # {http://www.opengis.net/gml/3.2}concatenatedOperationRef
from komle.write_bindings._nsgroup import usesOperation # {http://www.opengis.net/gml/3.2}usesOperation
from komle.write_bindings._nsgroup import passThroughOperationRef # {http://www.opengis.net/gml/3.2}passThroughOperationRef
from komle.write_bindings._nsgroup import usesMethod # {http://www.opengis.net/gml/3.2}usesMethod
from komle.write_bindings._nsgroup import conversionRef # {http://www.opengis.net/gml/3.2}conversionRef
from komle.write_bindings._nsgroup import transformationRef # {http://www.opengis.net/gml/3.2}transformationRef
from komle.write_bindings._nsgroup import valueOfParameter # {http://www.opengis.net/gml/3.2}valueOfParameter
from komle.write_bindings._nsgroup import valuesOfGroup # {http://www.opengis.net/gml/3.2}valuesOfGroup
from komle.write_bindings._nsgroup import usesParameter # {http://www.opengis.net/gml/3.2}usesParameter
from komle.write_bindings._nsgroup import operationMethodRef # {http://www.opengis.net/gml/3.2}operationMethodRef
from komle.write_bindings._nsgroup import abstractGeneralOperationParameterRef # {http://www.opengis.net/gml/3.2}abstractGeneralOperationParameterRef
from komle.write_bindings._nsgroup import operationParameterRef # {http://www.opengis.net/gml/3.2}operationParameterRef
from komle.write_bindings._nsgroup import includesParameter # {http://www.opengis.net/gml/3.2}includesParameter
from komle.write_bindings._nsgroup import operationParameterGroupRef # {http://www.opengis.net/gml/3.2}operationParameterGroupRef
from komle.write_bindings._nsgroup import referenceSystemRef # {http://www.opengis.net/gml/3.2}referenceSystemRef
from komle.write_bindings._nsgroup import crsRef # {http://www.opengis.net/gml/3.2}crsRef
from komle.write_bindings._nsgroup import coordinateSystemAxisRef # {http://www.opengis.net/gml/3.2}coordinateSystemAxisRef
from komle.write_bindings._nsgroup import usesAxis # {http://www.opengis.net/gml/3.2}usesAxis
from komle.write_bindings._nsgroup import coordinateSystemRef # {http://www.opengis.net/gml/3.2}coordinateSystemRef
from komle.write_bindings._nsgroup import ellipsoidalCSRef # {http://www.opengis.net/gml/3.2}ellipsoidalCSRef
from komle.write_bindings._nsgroup import cartesianCSRef # {http://www.opengis.net/gml/3.2}cartesianCSRef
from komle.write_bindings._nsgroup import verticalCSRef # {http://www.opengis.net/gml/3.2}verticalCSRef
from komle.write_bindings._nsgroup import temporalCSRef # {http://www.opengis.net/gml/3.2}temporalCSRef
from komle.write_bindings._nsgroup import linearCSRef # {http://www.opengis.net/gml/3.2}linearCSRef
from komle.write_bindings._nsgroup import userDefinedCSRef # {http://www.opengis.net/gml/3.2}userDefinedCSRef
from komle.write_bindings._nsgroup import sphericalCSRef # {http://www.opengis.net/gml/3.2}sphericalCSRef
from komle.write_bindings._nsgroup import polarCSRef # {http://www.opengis.net/gml/3.2}polarCSRef
from komle.write_bindings._nsgroup import cylindricalCSRef # {http://www.opengis.net/gml/3.2}cylindricalCSRef
from komle.write_bindings._nsgroup import obliqueCartesianCSRef # {http://www.opengis.net/gml/3.2}obliqueCartesianCSRef
from komle.write_bindings._nsgroup import singleCRSRef # {http://www.opengis.net/gml/3.2}singleCRSRef
from komle.write_bindings._nsgroup import definedByConversion # {http://www.opengis.net/gml/3.2}definedByConversion
from komle.write_bindings._nsgroup import includesSingleCRS # {http://www.opengis.net/gml/3.2}includesSingleCRS
from komle.write_bindings._nsgroup import compoundCRSRef # {http://www.opengis.net/gml/3.2}compoundCRSRef
from komle.write_bindings._nsgroup import usesEllipsoidalCS # {http://www.opengis.net/gml/3.2}usesEllipsoidalCS
from komle.write_bindings._nsgroup import usesCartesianCS # {http://www.opengis.net/gml/3.2}usesCartesianCS
from komle.write_bindings._nsgroup import usesSphericalCS # {http://www.opengis.net/gml/3.2}usesSphericalCS
from komle.write_bindings._nsgroup import usesGeodeticDatum # {http://www.opengis.net/gml/3.2}usesGeodeticDatum
from komle.write_bindings._nsgroup import usesVerticalCS # {http://www.opengis.net/gml/3.2}usesVerticalCS
from komle.write_bindings._nsgroup import usesVerticalDatum # {http://www.opengis.net/gml/3.2}usesVerticalDatum
from komle.write_bindings._nsgroup import verticalCRSRef # {http://www.opengis.net/gml/3.2}verticalCRSRef
from komle.write_bindings._nsgroup import baseGeographicCRS # {http://www.opengis.net/gml/3.2}baseGeographicCRS
from komle.write_bindings._nsgroup import projectedCRSRef # {http://www.opengis.net/gml/3.2}projectedCRSRef
from komle.write_bindings._nsgroup import usesCS # {http://www.opengis.net/gml/3.2}usesCS
from komle.write_bindings._nsgroup import derivedCRSRef # {http://www.opengis.net/gml/3.2}derivedCRSRef
from komle.write_bindings._nsgroup import usesEngineeringDatum # {http://www.opengis.net/gml/3.2}usesEngineeringDatum
from komle.write_bindings._nsgroup import engineeringCRSRef # {http://www.opengis.net/gml/3.2}engineeringCRSRef
from komle.write_bindings._nsgroup import usesAffineCS # {http://www.opengis.net/gml/3.2}usesAffineCS
from komle.write_bindings._nsgroup import usesImageDatum # {http://www.opengis.net/gml/3.2}usesImageDatum
from komle.write_bindings._nsgroup import usesObliqueCartesianCS # {http://www.opengis.net/gml/3.2}usesObliqueCartesianCS
from komle.write_bindings._nsgroup import imageCRSRef # {http://www.opengis.net/gml/3.2}imageCRSRef
from komle.write_bindings._nsgroup import usesTimeCS # {http://www.opengis.net/gml/3.2}usesTimeCS
from komle.write_bindings._nsgroup import usesTemporalCS # {http://www.opengis.net/gml/3.2}usesTemporalCS
from komle.write_bindings._nsgroup import usesTemporalDatum # {http://www.opengis.net/gml/3.2}usesTemporalDatum
from komle.write_bindings._nsgroup import temporalCRSRef # {http://www.opengis.net/gml/3.2}temporalCRSRef
from komle.write_bindings._nsgroup import geographicCRSRef # {http://www.opengis.net/gml/3.2}geographicCRSRef
from komle.write_bindings._nsgroup import geocentricCRSRef # {http://www.opengis.net/gml/3.2}geocentricCRSRef
from komle.write_bindings._nsgroup import member # {http://www.opengis.net/gml/3.2}member
from komle.write_bindings._nsgroup import metaDataProperty # {http://www.opengis.net/gml/3.2}metaDataProperty
from komle.write_bindings._nsgroup import pointRep # {http://www.opengis.net/gml/3.2}pointRep
from komle.write_bindings._nsgroup import location # {http://www.opengis.net/gml/3.2}location
from komle.write_bindings._nsgroup import LocationString # {http://www.opengis.net/gml/3.2}LocationString
from komle.write_bindings._nsgroup import featureMember # {http://www.opengis.net/gml/3.2}featureMember
from komle.write_bindings._nsgroup import featureProperty # {http://www.opengis.net/gml/3.2}featureProperty
from komle.write_bindings._nsgroup import AbstractFeatureCollection # {http://www.opengis.net/gml/3.2}AbstractFeatureCollection
from komle.write_bindings._nsgroup import definitionMember # {http://www.opengis.net/gml/3.2}definitionMember
from komle.write_bindings._nsgroup import definitionRef # {http://www.opengis.net/gml/3.2}definitionRef
from komle.write_bindings._nsgroup import MappingRule # {http://www.opengis.net/gml/3.2}MappingRule
from komle.write_bindings._nsgroup import centerOf # {http://www.opengis.net/gml/3.2}centerOf
from komle.write_bindings._nsgroup import position # {http://www.opengis.net/gml/3.2}position
from komle.write_bindings._nsgroup import extentOf # {http://www.opengis.net/gml/3.2}extentOf
from komle.write_bindings._nsgroup import edgeOf # {http://www.opengis.net/gml/3.2}edgeOf
from komle.write_bindings._nsgroup import centerLineOf # {http://www.opengis.net/gml/3.2}centerLineOf
from komle.write_bindings._nsgroup import multiLocation # {http://www.opengis.net/gml/3.2}multiLocation
from komle.write_bindings._nsgroup import multiCenterOf # {http://www.opengis.net/gml/3.2}multiCenterOf
from komle.write_bindings._nsgroup import multiPosition # {http://www.opengis.net/gml/3.2}multiPosition
from komle.write_bindings._nsgroup import multiCenterLineOf # {http://www.opengis.net/gml/3.2}multiCenterLineOf
from komle.write_bindings._nsgroup import multiEdgeOf # {http://www.opengis.net/gml/3.2}multiEdgeOf
from komle.write_bindings._nsgroup import multiCoverage # {http://www.opengis.net/gml/3.2}multiCoverage
from komle.write_bindings._nsgroup import multiExtentOf # {http://www.opengis.net/gml/3.2}multiExtentOf
from komle.write_bindings._nsgroup import multiPointDomain # {http://www.opengis.net/gml/3.2}multiPointDomain
from komle.write_bindings._nsgroup import multiCurveDomain # {http://www.opengis.net/gml/3.2}multiCurveDomain
from komle.write_bindings._nsgroup import multiSurfaceDomain # {http://www.opengis.net/gml/3.2}multiSurfaceDomain
from komle.write_bindings._nsgroup import multiSolidDomain # {http://www.opengis.net/gml/3.2}multiSolidDomain
from komle.write_bindings._nsgroup import gridDomain # {http://www.opengis.net/gml/3.2}gridDomain
from komle.write_bindings._nsgroup import rectifiedGridDomain # {http://www.opengis.net/gml/3.2}rectifiedGridDomain
from komle.write_bindings._nsgroup import generalOperationParameter # {http://www.opengis.net/gml/3.2}generalOperationParameter
from komle.write_bindings._nsgroup import MovingObjectStatus # {http://www.opengis.net/gml/3.2}MovingObjectStatus
from komle.write_bindings._nsgroup import status # {http://www.opengis.net/gml/3.2}status
from komle.write_bindings._nsgroup import statusReference # {http://www.opengis.net/gml/3.2}statusReference
from komle.write_bindings._nsgroup import topoComplexProperty # {http://www.opengis.net/gml/3.2}topoComplexProperty
from komle.write_bindings._nsgroup import multiPointProperty # {http://www.opengis.net/gml/3.2}multiPointProperty
from komle.write_bindings._nsgroup import multiCurveProperty # {http://www.opengis.net/gml/3.2}multiCurveProperty
from komle.write_bindings._nsgroup import multiSurfaceProperty # {http://www.opengis.net/gml/3.2}multiSurfaceProperty
from komle.write_bindings._nsgroup import multiSolidProperty # {http://www.opengis.net/gml/3.2}multiSolidProperty
from komle.write_bindings._nsgroup import multiGeometryProperty # {http://www.opengis.net/gml/3.2}multiGeometryProperty
from komle.write_bindings._nsgroup import Definition # {http://www.opengis.net/gml/3.2}Definition
from komle.write_bindings._nsgroup import dictionaryEntry # {http://www.opengis.net/gml/3.2}dictionaryEntry
from komle.write_bindings._nsgroup import direction # {http://www.opengis.net/gml/3.2}direction
from komle.write_bindings._nsgroup import dataSource # {http://www.opengis.net/gml/3.2}dataSource
from komle.write_bindings._nsgroup import dataSourceReference # {http://www.opengis.net/gml/3.2}dataSourceReference
from komle.write_bindings._nsgroup import DynamicFeature # {http://www.opengis.net/gml/3.2}DynamicFeature
from komle.write_bindings._nsgroup import dynamicMembers # {http://www.opengis.net/gml/3.2}dynamicMembers
from komle.write_bindings._nsgroup import boundedBy # {http://www.opengis.net/gml/3.2}boundedBy
from komle.write_bindings._nsgroup import EnvelopeWithTimePeriod # {http://www.opengis.net/gml/3.2}EnvelopeWithTimePeriod
from komle.write_bindings._nsgroup import locationReference # {http://www.opengis.net/gml/3.2}locationReference
from komle.write_bindings._nsgroup import AbstractGeometricAggregate # {http://www.opengis.net/gml/3.2}AbstractGeometricAggregate
from komle.write_bindings._nsgroup import geometryMember # {http://www.opengis.net/gml/3.2}geometryMember
from komle.write_bindings._nsgroup import pointMember # {http://www.opengis.net/gml/3.2}pointMember
from komle.write_bindings._nsgroup import solidMember # {http://www.opengis.net/gml/3.2}solidMember
from komle.write_bindings._nsgroup import vector # {http://www.opengis.net/gml/3.2}vector
from komle.write_bindings._nsgroup import AbstractGeometricPrimitive # {http://www.opengis.net/gml/3.2}AbstractGeometricPrimitive
from komle.write_bindings._nsgroup import pointProperty # {http://www.opengis.net/gml/3.2}pointProperty
from komle.write_bindings._nsgroup import curveProperty # {http://www.opengis.net/gml/3.2}curveProperty
from komle.write_bindings._nsgroup import surfaceProperty # {http://www.opengis.net/gml/3.2}surfaceProperty
from komle.write_bindings._nsgroup import GeometricComplex # {http://www.opengis.net/gml/3.2}GeometricComplex
from komle.write_bindings._nsgroup import baseCurve # {http://www.opengis.net/gml/3.2}baseCurve
from komle.write_bindings._nsgroup import Arc # {http://www.opengis.net/gml/3.2}Arc
from komle.write_bindings._nsgroup import ArcByBulge # {http://www.opengis.net/gml/3.2}ArcByBulge
from komle.write_bindings._nsgroup import CircleByCenterPoint # {http://www.opengis.net/gml/3.2}CircleByCenterPoint
from komle.write_bindings._nsgroup import Bezier # {http://www.opengis.net/gml/3.2}Bezier
from komle.write_bindings._nsgroup import Geodesic # {http://www.opengis.net/gml/3.2}Geodesic
from komle.write_bindings._nsgroup import baseSurface # {http://www.opengis.net/gml/3.2}baseSurface
from komle.write_bindings._nsgroup import curveMember # {http://www.opengis.net/gml/3.2}curveMember
from komle.write_bindings._nsgroup import AbstractGriddedSurface # {http://www.opengis.net/gml/3.2}AbstractGriddedSurface
from komle.write_bindings._nsgroup import solidProperty # {http://www.opengis.net/gml/3.2}solidProperty
from komle.write_bindings._nsgroup import surfaceMember # {http://www.opengis.net/gml/3.2}surfaceMember
from komle.write_bindings._nsgroup import abstractAssociationRole # {http://www.opengis.net/gml/3.2}abstractAssociationRole
from komle.write_bindings._nsgroup import abstractStrictAssociationRole # {http://www.opengis.net/gml/3.2}abstractStrictAssociationRole
from komle.write_bindings._nsgroup import abstractReference # {http://www.opengis.net/gml/3.2}abstractReference
from komle.write_bindings._nsgroup import description # {http://www.opengis.net/gml/3.2}description
from komle.write_bindings._nsgroup import descriptionReference # {http://www.opengis.net/gml/3.2}descriptionReference
from komle.write_bindings._nsgroup import Grid # {http://www.opengis.net/gml/3.2}Grid
from komle.write_bindings._nsgroup import measure # {http://www.opengis.net/gml/3.2}measure
from komle.write_bindings._nsgroup import Observation # {http://www.opengis.net/gml/3.2}Observation
from komle.write_bindings._nsgroup import using # {http://www.opengis.net/gml/3.2}using
from komle.write_bindings._nsgroup import target # {http://www.opengis.net/gml/3.2}target
from komle.write_bindings._nsgroup import subject # {http://www.opengis.net/gml/3.2}subject
from komle.write_bindings._nsgroup import resultOf # {http://www.opengis.net/gml/3.2}resultOf
from komle.write_bindings._nsgroup import domainOfValidity # {http://www.opengis.net/gml/3.2}domainOfValidity
from komle.write_bindings._nsgroup import AbstractTimePrimitive # {http://www.opengis.net/gml/3.2}AbstractTimePrimitive
from komle.write_bindings._nsgroup import validTime # {http://www.opengis.net/gml/3.2}validTime
from komle.write_bindings._nsgroup import AbstractTimeComplex # {http://www.opengis.net/gml/3.2}AbstractTimeComplex
from komle.write_bindings._nsgroup import timeInterval # {http://www.opengis.net/gml/3.2}timeInterval
from komle.write_bindings._nsgroup import AbstractTopoPrimitive # {http://www.opengis.net/gml/3.2}AbstractTopoPrimitive
from komle.write_bindings._nsgroup import directedNode # {http://www.opengis.net/gml/3.2}directedNode
from komle.write_bindings._nsgroup import directedEdge # {http://www.opengis.net/gml/3.2}directedEdge
from komle.write_bindings._nsgroup import directedFace # {http://www.opengis.net/gml/3.2}directedFace
from komle.write_bindings._nsgroup import directedTopoSolid # {http://www.opengis.net/gml/3.2}directedTopoSolid
from komle.write_bindings._nsgroup import TopoPoint # {http://www.opengis.net/gml/3.2}TopoPoint
from komle.write_bindings._nsgroup import TopoCurve # {http://www.opengis.net/gml/3.2}TopoCurve
from komle.write_bindings._nsgroup import TopoSurface # {http://www.opengis.net/gml/3.2}TopoSurface
from komle.write_bindings._nsgroup import TopoVolume # {http://www.opengis.net/gml/3.2}TopoVolume
from komle.write_bindings._nsgroup import TopoComplex # {http://www.opengis.net/gml/3.2}TopoComplex
from komle.write_bindings._nsgroup import subComplex # {http://www.opengis.net/gml/3.2}subComplex
from komle.write_bindings._nsgroup import superComplex # {http://www.opengis.net/gml/3.2}superComplex
from komle.write_bindings._nsgroup import maximalComplex # {http://www.opengis.net/gml/3.2}maximalComplex
from komle.write_bindings._nsgroup import topoPrimitiveMember # {http://www.opengis.net/gml/3.2}topoPrimitiveMember
from komle.write_bindings._nsgroup import unitOfMeasure # {http://www.opengis.net/gml/3.2}unitOfMeasure
from komle.write_bindings._nsgroup import quantityType # {http://www.opengis.net/gml/3.2}quantityType
from komle.write_bindings._nsgroup import quantityTypeReference # {http://www.opengis.net/gml/3.2}quantityTypeReference
from komle.write_bindings._nsgroup import Boolean_ as Boolean # {http://www.opengis.net/gml/3.2}Boolean
from komle.write_bindings._nsgroup import BooleanList # {http://www.opengis.net/gml/3.2}BooleanList
from komle.write_bindings._nsgroup import Category # {http://www.opengis.net/gml/3.2}Category
from komle.write_bindings._nsgroup import Count # {http://www.opengis.net/gml/3.2}Count
from komle.write_bindings._nsgroup import CountList # {http://www.opengis.net/gml/3.2}CountList
from komle.write_bindings._nsgroup import valueProperty # {http://www.opengis.net/gml/3.2}valueProperty
from komle.write_bindings._nsgroup import valueComponent # {http://www.opengis.net/gml/3.2}valueComponent
from komle.write_bindings._nsgroup import ValueArray # {http://www.opengis.net/gml/3.2}ValueArray
from komle.write_bindings._nsgroup import AbstractDiscreteCoverage # {http://www.opengis.net/gml/3.2}AbstractDiscreteCoverage
from komle.write_bindings._nsgroup import AbstractContinuousCoverage # {http://www.opengis.net/gml/3.2}AbstractContinuousCoverage
from komle.write_bindings._nsgroup import MultiPointCoverage # {http://www.opengis.net/gml/3.2}MultiPointCoverage
from komle.write_bindings._nsgroup import MultiCurveCoverage # {http://www.opengis.net/gml/3.2}MultiCurveCoverage
from komle.write_bindings._nsgroup import MultiSurfaceCoverage # {http://www.opengis.net/gml/3.2}MultiSurfaceCoverage
from komle.write_bindings._nsgroup import MultiSolidCoverage # {http://www.opengis.net/gml/3.2}MultiSolidCoverage
from komle.write_bindings._nsgroup import GridCoverage # {http://www.opengis.net/gml/3.2}GridCoverage
from komle.write_bindings._nsgroup import RectifiedGridCoverage # {http://www.opengis.net/gml/3.2}RectifiedGridCoverage
from komle.write_bindings._nsgroup import greenwichLongitude # {http://www.opengis.net/gml/3.2}greenwichLongitude
from komle.write_bindings._nsgroup import priorityLocation # {http://www.opengis.net/gml/3.2}priorityLocation
from komle.write_bindings._nsgroup import FeatureCollection # {http://www.opengis.net/gml/3.2}FeatureCollection
from komle.write_bindings._nsgroup import DefinitionCollection # {http://www.opengis.net/gml/3.2}DefinitionCollection
from komle.write_bindings._nsgroup import DefinitionProxy # {http://www.opengis.net/gml/3.2}DefinitionProxy
from komle.write_bindings._nsgroup import Dictionary # {http://www.opengis.net/gml/3.2}Dictionary
from komle.write_bindings._nsgroup import DynamicFeatureCollection # {http://www.opengis.net/gml/3.2}DynamicFeatureCollection
from komle.write_bindings._nsgroup import MultiGeometry # {http://www.opengis.net/gml/3.2}MultiGeometry
from komle.write_bindings._nsgroup import MultiPoint # {http://www.opengis.net/gml/3.2}MultiPoint
from komle.write_bindings._nsgroup import MultiCurve # {http://www.opengis.net/gml/3.2}MultiCurve
from komle.write_bindings._nsgroup import MultiSurface # {http://www.opengis.net/gml/3.2}MultiSurface
from komle.write_bindings._nsgroup import MultiSolid # {http://www.opengis.net/gml/3.2}MultiSolid
from komle.write_bindings._nsgroup import Point # {http://www.opengis.net/gml/3.2}Point
from komle.write_bindings._nsgroup import AbstractCurve # {http://www.opengis.net/gml/3.2}AbstractCurve
from komle.write_bindings._nsgroup import AbstractSurface # {http://www.opengis.net/gml/3.2}AbstractSurface
from komle.write_bindings._nsgroup import Circle # {http://www.opengis.net/gml/3.2}Circle
from komle.write_bindings._nsgroup import Cone # {http://www.opengis.net/gml/3.2}Cone
from komle.write_bindings._nsgroup import Cylinder # {http://www.opengis.net/gml/3.2}Cylinder
from komle.write_bindings._nsgroup import Sphere # {http://www.opengis.net/gml/3.2}Sphere
from komle.write_bindings._nsgroup import AbstractSolid # {http://www.opengis.net/gml/3.2}AbstractSolid
from komle.write_bindings._nsgroup import RectifiedGrid # {http://www.opengis.net/gml/3.2}RectifiedGrid
from komle.write_bindings._nsgroup import angle # {http://www.opengis.net/gml/3.2}angle
from komle.write_bindings._nsgroup import DirectedObservation # {http://www.opengis.net/gml/3.2}DirectedObservation
from komle.write_bindings._nsgroup import AbstractTimeGeometricPrimitive # {http://www.opengis.net/gml/3.2}AbstractTimeGeometricPrimitive
from komle.write_bindings._nsgroup import TimeReferenceSystem # {http://www.opengis.net/gml/3.2}TimeReferenceSystem
from komle.write_bindings._nsgroup import TimeCalendarEra # {http://www.opengis.net/gml/3.2}TimeCalendarEra
from komle.write_bindings._nsgroup import TimeOrdinalEra # {http://www.opengis.net/gml/3.2}TimeOrdinalEra
from komle.write_bindings._nsgroup import AbstractTimeTopologyPrimitive # {http://www.opengis.net/gml/3.2}AbstractTimeTopologyPrimitive
from komle.write_bindings._nsgroup import TimeTopologyComplex # {http://www.opengis.net/gml/3.2}TimeTopologyComplex
from komle.write_bindings._nsgroup import Node # {http://www.opengis.net/gml/3.2}Node
from komle.write_bindings._nsgroup import Edge # {http://www.opengis.net/gml/3.2}Edge
from komle.write_bindings._nsgroup import Face # {http://www.opengis.net/gml/3.2}Face
from komle.write_bindings._nsgroup import TopoSolid # {http://www.opengis.net/gml/3.2}TopoSolid
from komle.write_bindings._nsgroup import UnitDefinition # {http://www.opengis.net/gml/3.2}UnitDefinition
from komle.write_bindings._nsgroup import derivationUnitTerm # {http://www.opengis.net/gml/3.2}derivationUnitTerm
from komle.write_bindings._nsgroup import conversionToPreferredUnit # {http://www.opengis.net/gml/3.2}conversionToPreferredUnit
from komle.write_bindings._nsgroup import roughConversionToPreferredUnit # {http://www.opengis.net/gml/3.2}roughConversionToPreferredUnit
from komle.write_bindings._nsgroup import CategoryList # {http://www.opengis.net/gml/3.2}CategoryList
from komle.write_bindings._nsgroup import Quantity # {http://www.opengis.net/gml/3.2}Quantity
from komle.write_bindings._nsgroup import QuantityList # {http://www.opengis.net/gml/3.2}QuantityList
from komle.write_bindings._nsgroup import CountExtent # {http://www.opengis.net/gml/3.2}CountExtent
from komle.write_bindings._nsgroup import AbstractCoordinateOperation # {http://www.opengis.net/gml/3.2}AbstractCoordinateOperation
from komle.write_bindings._nsgroup import AbstractSingleOperation # {http://www.opengis.net/gml/3.2}AbstractSingleOperation
from komle.write_bindings._nsgroup import OperationMethod # {http://www.opengis.net/gml/3.2}OperationMethod
from komle.write_bindings._nsgroup import AbstractGeneralOperationParameter # {http://www.opengis.net/gml/3.2}AbstractGeneralOperationParameter
from komle.write_bindings._nsgroup import AbstractSingleCRS # {http://www.opengis.net/gml/3.2}AbstractSingleCRS
from komle.write_bindings._nsgroup import CoordinateSystemAxis # {http://www.opengis.net/gml/3.2}CoordinateSystemAxis
from komle.write_bindings._nsgroup import AbstractCoordinateSystem # {http://www.opengis.net/gml/3.2}AbstractCoordinateSystem
from komle.write_bindings._nsgroup import AbstractDatum # {http://www.opengis.net/gml/3.2}AbstractDatum
from komle.write_bindings._nsgroup import Ellipsoid # {http://www.opengis.net/gml/3.2}Ellipsoid
from komle.write_bindings._nsgroup import PrimeMeridian # {http://www.opengis.net/gml/3.2}PrimeMeridian
from komle.write_bindings._nsgroup import AbstractOperation # {http://www.opengis.net/gml/3.2}AbstractOperation
from komle.write_bindings._nsgroup import LineString # {http://www.opengis.net/gml/3.2}LineString
from komle.write_bindings._nsgroup import Polygon # {http://www.opengis.net/gml/3.2}Polygon
from komle.write_bindings._nsgroup import AbstractRing # {http://www.opengis.net/gml/3.2}AbstractRing
from komle.write_bindings._nsgroup import CompositeCurve # {http://www.opengis.net/gml/3.2}CompositeCurve
from komle.write_bindings._nsgroup import CompositeSurface # {http://www.opengis.net/gml/3.2}CompositeSurface
from komle.write_bindings._nsgroup import CompositeSolid # {http://www.opengis.net/gml/3.2}CompositeSolid
from komle.write_bindings._nsgroup import Curve # {http://www.opengis.net/gml/3.2}Curve
from komle.write_bindings._nsgroup import OrientableCurve # {http://www.opengis.net/gml/3.2}OrientableCurve
from komle.write_bindings._nsgroup import Surface # {http://www.opengis.net/gml/3.2}Surface
from komle.write_bindings._nsgroup import OrientableSurface # {http://www.opengis.net/gml/3.2}OrientableSurface
from komle.write_bindings._nsgroup import PolyhedralSurface # {http://www.opengis.net/gml/3.2}PolyhedralSurface
from komle.write_bindings._nsgroup import TriangulatedSurface # {http://www.opengis.net/gml/3.2}TriangulatedSurface
from komle.write_bindings._nsgroup import Solid # {http://www.opengis.net/gml/3.2}Solid
from komle.write_bindings._nsgroup import Shell # {http://www.opengis.net/gml/3.2}Shell
from komle.write_bindings._nsgroup import DirectedObservationAtDistance # {http://www.opengis.net/gml/3.2}DirectedObservationAtDistance
from komle.write_bindings._nsgroup import AbstractCRS # {http://www.opengis.net/gml/3.2}AbstractCRS
from komle.write_bindings._nsgroup import TimeInstant # {http://www.opengis.net/gml/3.2}TimeInstant
from komle.write_bindings._nsgroup import TimePeriod # {http://www.opengis.net/gml/3.2}TimePeriod
from komle.write_bindings._nsgroup import TimeCoordinateSystem # {http://www.opengis.net/gml/3.2}TimeCoordinateSystem
from komle.write_bindings._nsgroup import TimeCalendar # {http://www.opengis.net/gml/3.2}TimeCalendar
from komle.write_bindings._nsgroup import TimeClock # {http://www.opengis.net/gml/3.2}TimeClock
from komle.write_bindings._nsgroup import TimeOrdinalReferenceSystem # {http://www.opengis.net/gml/3.2}TimeOrdinalReferenceSystem
from komle.write_bindings._nsgroup import TimeNode # {http://www.opengis.net/gml/3.2}TimeNode
from komle.write_bindings._nsgroup import TimeEdge # {http://www.opengis.net/gml/3.2}TimeEdge
from komle.write_bindings._nsgroup import BaseUnit # {http://www.opengis.net/gml/3.2}BaseUnit
from komle.write_bindings._nsgroup import DerivedUnit # {http://www.opengis.net/gml/3.2}DerivedUnit
from komle.write_bindings._nsgroup import ConventionalUnit # {http://www.opengis.net/gml/3.2}ConventionalUnit
from komle.write_bindings._nsgroup import CategoryExtent # {http://www.opengis.net/gml/3.2}CategoryExtent
from komle.write_bindings._nsgroup import QuantityExtent # {http://www.opengis.net/gml/3.2}QuantityExtent
from komle.write_bindings._nsgroup import AbstractGeneralConversion # {http://www.opengis.net/gml/3.2}AbstractGeneralConversion
from komle.write_bindings._nsgroup import AbstractGeneralTransformation # {http://www.opengis.net/gml/3.2}AbstractGeneralTransformation
from komle.write_bindings._nsgroup import ConcatenatedOperation # {http://www.opengis.net/gml/3.2}ConcatenatedOperation
from komle.write_bindings._nsgroup import PassThroughOperation # {http://www.opengis.net/gml/3.2}PassThroughOperation
from komle.write_bindings._nsgroup import OperationParameter # {http://www.opengis.net/gml/3.2}OperationParameter
from komle.write_bindings._nsgroup import OperationParameterGroup # {http://www.opengis.net/gml/3.2}OperationParameterGroup
from komle.write_bindings._nsgroup import AbstractGeneralDerivedCRS # {http://www.opengis.net/gml/3.2}AbstractGeneralDerivedCRS
from komle.write_bindings._nsgroup import CompoundCRS # {http://www.opengis.net/gml/3.2}CompoundCRS
from komle.write_bindings._nsgroup import GeodeticCRS # {http://www.opengis.net/gml/3.2}GeodeticCRS
from komle.write_bindings._nsgroup import VerticalCRS # {http://www.opengis.net/gml/3.2}VerticalCRS
from komle.write_bindings._nsgroup import EngineeringCRS # {http://www.opengis.net/gml/3.2}EngineeringCRS
from komle.write_bindings._nsgroup import ImageCRS # {http://www.opengis.net/gml/3.2}ImageCRS
from komle.write_bindings._nsgroup import TemporalCRS # {http://www.opengis.net/gml/3.2}TemporalCRS
from komle.write_bindings._nsgroup import EllipsoidalCS # {http://www.opengis.net/gml/3.2}EllipsoidalCS
from komle.write_bindings._nsgroup import CartesianCS # {http://www.opengis.net/gml/3.2}CartesianCS
from komle.write_bindings._nsgroup import VerticalCS # {http://www.opengis.net/gml/3.2}VerticalCS
from komle.write_bindings._nsgroup import TimeCS # {http://www.opengis.net/gml/3.2}TimeCS
from komle.write_bindings._nsgroup import LinearCS # {http://www.opengis.net/gml/3.2}LinearCS
from komle.write_bindings._nsgroup import UserDefinedCS # {http://www.opengis.net/gml/3.2}UserDefinedCS
from komle.write_bindings._nsgroup import SphericalCS # {http://www.opengis.net/gml/3.2}SphericalCS
from komle.write_bindings._nsgroup import PolarCS # {http://www.opengis.net/gml/3.2}PolarCS
from komle.write_bindings._nsgroup import CylindricalCS # {http://www.opengis.net/gml/3.2}CylindricalCS
from komle.write_bindings._nsgroup import AffineCS # {http://www.opengis.net/gml/3.2}AffineCS
from komle.write_bindings._nsgroup import GeodeticDatum # {http://www.opengis.net/gml/3.2}GeodeticDatum
from komle.write_bindings._nsgroup import EngineeringDatum # {http://www.opengis.net/gml/3.2}EngineeringDatum
from komle.write_bindings._nsgroup import ImageDatum # {http://www.opengis.net/gml/3.2}ImageDatum
from komle.write_bindings._nsgroup import VerticalDatum # {http://www.opengis.net/gml/3.2}VerticalDatum
from komle.write_bindings._nsgroup import TemporalCS # {http://www.opengis.net/gml/3.2}TemporalCS
from komle.write_bindings._nsgroup import ObliqueCartesianCS # {http://www.opengis.net/gml/3.2}ObliqueCartesianCS
from komle.write_bindings._nsgroup import GeographicCRS # {http://www.opengis.net/gml/3.2}GeographicCRS
from komle.write_bindings._nsgroup import GeocentricCRS # {http://www.opengis.net/gml/3.2}GeocentricCRS
from komle.write_bindings._nsgroup import LinearRing # {http://www.opengis.net/gml/3.2}LinearRing
from komle.write_bindings._nsgroup import Ring # {http://www.opengis.net/gml/3.2}Ring
from komle.write_bindings._nsgroup import Tin # {http://www.opengis.net/gml/3.2}Tin
from komle.write_bindings._nsgroup import Conversion # {http://www.opengis.net/gml/3.2}Conversion
from komle.write_bindings._nsgroup import Transformation # {http://www.opengis.net/gml/3.2}Transformation
from komle.write_bindings._nsgroup import ProjectedCRS # {http://www.opengis.net/gml/3.2}ProjectedCRS
from komle.write_bindings._nsgroup import DerivedCRS # {http://www.opengis.net/gml/3.2}DerivedCRS
from komle.write_bindings._nsgroup import TemporalDatum # {http://www.opengis.net/gml/3.2}TemporalDatum
from komle.write_bindings._nsgroup import STD_ANON # None
from komle.write_bindings._nsgroup import STD_ANON_ # None
from komle.write_bindings._nsgroup import SignType # {http://www.opengis.net/gml/3.2}SignType
from komle.write_bindings._nsgroup import CodeType # {http://www.opengis.net/gml/3.2}CodeType
from komle.write_bindings._nsgroup import STD_ANON_2 # None
from komle.write_bindings._nsgroup import UomSymbol # {http://www.opengis.net/gml/3.2}UomSymbol
from komle.write_bindings._nsgroup import UomURI # {http://www.opengis.net/gml/3.2}UomURI
from komle.write_bindings._nsgroup import CoordinatesType # {http://www.opengis.net/gml/3.2}CoordinatesType
from komle.write_bindings._nsgroup import booleanList # {http://www.opengis.net/gml/3.2}booleanList
from komle.write_bindings._nsgroup import doubleList # {http://www.opengis.net/gml/3.2}doubleList
from komle.write_bindings._nsgroup import integerList # {http://www.opengis.net/gml/3.2}integerList
from komle.write_bindings._nsgroup import NameList # {http://www.opengis.net/gml/3.2}NameList
from komle.write_bindings._nsgroup import NCNameList # {http://www.opengis.net/gml/3.2}NCNameList
from komle.write_bindings._nsgroup import QNameList # {http://www.opengis.net/gml/3.2}QNameList
from komle.write_bindings._nsgroup import AbstractGeneralParameterValueType # {http://www.opengis.net/gml/3.2}AbstractGeneralParameterValueType
from komle.write_bindings._nsgroup import AbstractGeneralParameterValuePropertyType # {http://www.opengis.net/gml/3.2}AbstractGeneralParameterValuePropertyType
from komle.write_bindings._nsgroup import RangeSetType # {http://www.opengis.net/gml/3.2}RangeSetType
from komle.write_bindings._nsgroup import DataBlockType # {http://www.opengis.net/gml/3.2}DataBlockType
from komle.write_bindings._nsgroup import FileType # {http://www.opengis.net/gml/3.2}FileType
from komle.write_bindings._nsgroup import CoverageFunctionType # {http://www.opengis.net/gml/3.2}CoverageFunctionType
from komle.write_bindings._nsgroup import MappingRuleType # {http://www.opengis.net/gml/3.2}MappingRuleType
from komle.write_bindings._nsgroup import GridFunctionType # {http://www.opengis.net/gml/3.2}GridFunctionType
from komle.write_bindings._nsgroup import SequenceRuleEnumeration # {http://www.opengis.net/gml/3.2}SequenceRuleEnumeration
from komle.write_bindings._nsgroup import AxisDirection # {http://www.opengis.net/gml/3.2}AxisDirection
from komle.write_bindings._nsgroup import CTD_ANON # None
from komle.write_bindings._nsgroup import CTD_ANON_ # None
from komle.write_bindings._nsgroup import SuccessionType # {http://www.opengis.net/gml/3.2}SuccessionType
from komle.write_bindings._nsgroup import DMSAngleType # {http://www.opengis.net/gml/3.2}DMSAngleType
from komle.write_bindings._nsgroup import STD_ANON_3 # None
from komle.write_bindings._nsgroup import DegreeValueType # {http://www.opengis.net/gml/3.2}DegreeValueType
from komle.write_bindings._nsgroup import DecimalMinutesType # {http://www.opengis.net/gml/3.2}DecimalMinutesType
from komle.write_bindings._nsgroup import ArcMinutesType # {http://www.opengis.net/gml/3.2}ArcMinutesType
from komle.write_bindings._nsgroup import ArcSecondsType # {http://www.opengis.net/gml/3.2}ArcSecondsType
from komle.write_bindings._nsgroup import AngleChoiceType # {http://www.opengis.net/gml/3.2}AngleChoiceType
from komle.write_bindings._nsgroup import ArrayAssociationType # {http://www.opengis.net/gml/3.2}ArrayAssociationType
from komle.write_bindings._nsgroup import AbstractMetaDataType # {http://www.opengis.net/gml/3.2}AbstractMetaDataType
from komle.write_bindings._nsgroup import FeatureArrayPropertyType # {http://www.opengis.net/gml/3.2}FeatureArrayPropertyType
from komle.write_bindings._nsgroup import IndirectEntryType # {http://www.opengis.net/gml/3.2}IndirectEntryType
from komle.write_bindings._nsgroup import IncrementOrder # {http://www.opengis.net/gml/3.2}IncrementOrder
from komle.write_bindings._nsgroup import DirectionVectorType # {http://www.opengis.net/gml/3.2}DirectionVectorType
from komle.write_bindings._nsgroup import DirectionDescriptionType # {http://www.opengis.net/gml/3.2}DirectionDescriptionType
from komle.write_bindings._nsgroup import CompassPointEnumeration # {http://www.opengis.net/gml/3.2}CompassPointEnumeration
from komle.write_bindings._nsgroup import HistoryPropertyType # {http://www.opengis.net/gml/3.2}HistoryPropertyType
from komle.write_bindings._nsgroup import AbstractFeatureMemberType # {http://www.opengis.net/gml/3.2}AbstractFeatureMemberType
from komle.write_bindings._nsgroup import GeometryArrayPropertyType # {http://www.opengis.net/gml/3.2}GeometryArrayPropertyType
from komle.write_bindings._nsgroup import PointArrayPropertyType # {http://www.opengis.net/gml/3.2}PointArrayPropertyType
from komle.write_bindings._nsgroup import CurveArrayPropertyType # {http://www.opengis.net/gml/3.2}CurveArrayPropertyType
from komle.write_bindings._nsgroup import SurfaceArrayPropertyType # {http://www.opengis.net/gml/3.2}SurfaceArrayPropertyType
from komle.write_bindings._nsgroup import AbstractRingPropertyType # {http://www.opengis.net/gml/3.2}AbstractRingPropertyType
from komle.write_bindings._nsgroup import LinearRingPropertyType # {http://www.opengis.net/gml/3.2}LinearRingPropertyType
from komle.write_bindings._nsgroup import AbstractCurveSegmentType # {http://www.opengis.net/gml/3.2}AbstractCurveSegmentType
from komle.write_bindings._nsgroup import CurveSegmentArrayPropertyType # {http://www.opengis.net/gml/3.2}CurveSegmentArrayPropertyType
from komle.write_bindings._nsgroup import CurveInterpolationType # {http://www.opengis.net/gml/3.2}CurveInterpolationType
from komle.write_bindings._nsgroup import KnotType # {http://www.opengis.net/gml/3.2}KnotType
from komle.write_bindings._nsgroup import KnotPropertyType # {http://www.opengis.net/gml/3.2}KnotPropertyType
from komle.write_bindings._nsgroup import KnotTypesType # {http://www.opengis.net/gml/3.2}KnotTypesType
from komle.write_bindings._nsgroup import AffinePlacementType # {http://www.opengis.net/gml/3.2}AffinePlacementType
from komle.write_bindings._nsgroup import CTD_ANON_2 # None
from komle.write_bindings._nsgroup import AbstractSurfacePatchType # {http://www.opengis.net/gml/3.2}AbstractSurfacePatchType
from komle.write_bindings._nsgroup import SurfacePatchArrayPropertyType # {http://www.opengis.net/gml/3.2}SurfacePatchArrayPropertyType
from komle.write_bindings._nsgroup import SurfaceInterpolationType # {http://www.opengis.net/gml/3.2}SurfaceInterpolationType
from komle.write_bindings._nsgroup import RingPropertyType # {http://www.opengis.net/gml/3.2}RingPropertyType
from komle.write_bindings._nsgroup import CTD_ANON_3 # None
from komle.write_bindings._nsgroup import CTD_ANON_4 # None
from komle.write_bindings._nsgroup import CTD_ANON_5 # None
from komle.write_bindings._nsgroup import LineStringSegmentArrayPropertyType # {http://www.opengis.net/gml/3.2}LineStringSegmentArrayPropertyType
from komle.write_bindings._nsgroup import SolidArrayPropertyType # {http://www.opengis.net/gml/3.2}SolidArrayPropertyType
from komle.write_bindings._nsgroup import ShellPropertyType # {http://www.opengis.net/gml/3.2}ShellPropertyType
from komle.write_bindings._nsgroup import AbstractGMLType # {http://www.opengis.net/gml/3.2}AbstractGMLType
from komle.write_bindings._nsgroup import InlinePropertyType # {http://www.opengis.net/gml/3.2}InlinePropertyType
from komle.write_bindings._nsgroup import AbstractMemberType # {http://www.opengis.net/gml/3.2}AbstractMemberType
from komle.write_bindings._nsgroup import AggregationType # {http://www.opengis.net/gml/3.2}AggregationType
from komle.write_bindings._nsgroup import AbstractMetadataPropertyType # {http://www.opengis.net/gml/3.2}AbstractMetadataPropertyType
from komle.write_bindings._nsgroup import GridLimitsType # {http://www.opengis.net/gml/3.2}GridLimitsType
from komle.write_bindings._nsgroup import GridEnvelopeType # {http://www.opengis.net/gml/3.2}GridEnvelopeType
from komle.write_bindings._nsgroup import STD_ANON_4 # None
from komle.write_bindings._nsgroup import TimeIndeterminateValueType # {http://www.opengis.net/gml/3.2}TimeIndeterminateValueType
from komle.write_bindings._nsgroup import TimePositionUnion # {http://www.opengis.net/gml/3.2}TimePositionUnion
from komle.write_bindings._nsgroup import CalDate # {http://www.opengis.net/gml/3.2}CalDate
from komle.write_bindings._nsgroup import STD_ANON_5 # None
from komle.write_bindings._nsgroup import STD_ANON_6 # None
from komle.write_bindings._nsgroup import TopoPointPropertyType # {http://www.opengis.net/gml/3.2}TopoPointPropertyType
from komle.write_bindings._nsgroup import TopoCurvePropertyType # {http://www.opengis.net/gml/3.2}TopoCurvePropertyType
from komle.write_bindings._nsgroup import TopoSurfacePropertyType # {http://www.opengis.net/gml/3.2}TopoSurfacePropertyType
from komle.write_bindings._nsgroup import TopoVolumePropertyType # {http://www.opengis.net/gml/3.2}TopoVolumePropertyType
from komle.write_bindings._nsgroup import TopoPrimitiveArrayAssociationType # {http://www.opengis.net/gml/3.2}TopoPrimitiveArrayAssociationType
from komle.write_bindings._nsgroup import FormulaType # {http://www.opengis.net/gml/3.2}FormulaType
from komle.write_bindings._nsgroup import ValueArrayPropertyType # {http://www.opengis.net/gml/3.2}ValueArrayPropertyType
from komle.write_bindings._nsgroup import NilReasonType # {http://www.opengis.net/gml/3.2}NilReasonType
from komle.write_bindings._nsgroup import NilReasonEnumeration # {http://www.opengis.net/gml/3.2}NilReasonEnumeration
from komle.write_bindings._nsgroup import booleanOrNilReason # {http://www.opengis.net/gml/3.2}booleanOrNilReason
from komle.write_bindings._nsgroup import doubleOrNilReason # {http://www.opengis.net/gml/3.2}doubleOrNilReason
from komle.write_bindings._nsgroup import integerOrNilReason # {http://www.opengis.net/gml/3.2}integerOrNilReason
from komle.write_bindings._nsgroup import NameOrNilReason # {http://www.opengis.net/gml/3.2}NameOrNilReason
from komle.write_bindings._nsgroup import stringOrNilReason # {http://www.opengis.net/gml/3.2}stringOrNilReason
from komle.write_bindings._nsgroup import CodeWithAuthorityType # {http://www.opengis.net/gml/3.2}CodeWithAuthorityType
from komle.write_bindings._nsgroup import UomIdentifier # {http://www.opengis.net/gml/3.2}UomIdentifier
from komle.write_bindings._nsgroup import CodeListType # {http://www.opengis.net/gml/3.2}CodeListType
from komle.write_bindings._nsgroup import ParameterValueType # {http://www.opengis.net/gml/3.2}ParameterValueType
from komle.write_bindings._nsgroup import ParameterValueGroupType # {http://www.opengis.net/gml/3.2}ParameterValueGroupType
from komle.write_bindings._nsgroup import AxisDirectionList # {http://www.opengis.net/gml/3.2}AxisDirectionList
from komle.write_bindings._nsgroup import DegreesType # {http://www.opengis.net/gml/3.2}DegreesType
from komle.write_bindings._nsgroup import BagType # {http://www.opengis.net/gml/3.2}BagType
from komle.write_bindings._nsgroup import ArrayType # {http://www.opengis.net/gml/3.2}ArrayType
from komle.write_bindings._nsgroup import GenericMetaDataType # {http://www.opengis.net/gml/3.2}GenericMetaDataType
from komle.write_bindings._nsgroup import DefinitionBaseType # {http://www.opengis.net/gml/3.2}DefinitionBaseType
from komle.write_bindings._nsgroup import AbstractTimeSliceType # {http://www.opengis.net/gml/3.2}AbstractTimeSliceType
from komle.write_bindings._nsgroup import AbstractFeatureType # {http://www.opengis.net/gml/3.2}AbstractFeatureType
from komle.write_bindings._nsgroup import AbstractGeometryType # {http://www.opengis.net/gml/3.2}AbstractGeometryType
from komle.write_bindings._nsgroup import DirectPositionType # {http://www.opengis.net/gml/3.2}DirectPositionType
from komle.write_bindings._nsgroup import DirectPositionListType # {http://www.opengis.net/gml/3.2}DirectPositionListType
from komle.write_bindings._nsgroup import STD_ANON_7 # None
from komle.write_bindings._nsgroup import EnvelopeType # {http://www.opengis.net/gml/3.2}EnvelopeType
from komle.write_bindings._nsgroup import LineStringSegmentType # {http://www.opengis.net/gml/3.2}LineStringSegmentType
from komle.write_bindings._nsgroup import ArcStringType # {http://www.opengis.net/gml/3.2}ArcStringType
from komle.write_bindings._nsgroup import ArcStringByBulgeType # {http://www.opengis.net/gml/3.2}ArcStringByBulgeType
from komle.write_bindings._nsgroup import ArcByCenterPointType # {http://www.opengis.net/gml/3.2}ArcByCenterPointType
from komle.write_bindings._nsgroup import CubicSplineType # {http://www.opengis.net/gml/3.2}CubicSplineType
from komle.write_bindings._nsgroup import BSplineType # {http://www.opengis.net/gml/3.2}BSplineType
from komle.write_bindings._nsgroup import OffsetCurveType # {http://www.opengis.net/gml/3.2}OffsetCurveType
from komle.write_bindings._nsgroup import ClothoidType # {http://www.opengis.net/gml/3.2}ClothoidType
from komle.write_bindings._nsgroup import GeodesicStringType # {http://www.opengis.net/gml/3.2}GeodesicStringType
from komle.write_bindings._nsgroup import PolygonPatchType # {http://www.opengis.net/gml/3.2}PolygonPatchType
from komle.write_bindings._nsgroup import TriangleType # {http://www.opengis.net/gml/3.2}TriangleType
from komle.write_bindings._nsgroup import RectangleType # {http://www.opengis.net/gml/3.2}RectangleType
from komle.write_bindings._nsgroup import AbstractParametricCurveSurfaceType # {http://www.opengis.net/gml/3.2}AbstractParametricCurveSurfaceType
from komle.write_bindings._nsgroup import AbstractTimeObjectType # {http://www.opengis.net/gml/3.2}AbstractTimeObjectType
from komle.write_bindings._nsgroup import TimePositionType # {http://www.opengis.net/gml/3.2}TimePositionType
from komle.write_bindings._nsgroup import TimeUnitType # {http://www.opengis.net/gml/3.2}TimeUnitType
from komle.write_bindings._nsgroup import AbstractTopologyType # {http://www.opengis.net/gml/3.2}AbstractTopologyType
from komle.write_bindings._nsgroup import CompositeValueType # {http://www.opengis.net/gml/3.2}CompositeValueType
from komle.write_bindings._nsgroup import MeasureType # {http://www.opengis.net/gml/3.2}MeasureType
from komle.write_bindings._nsgroup import booleanOrNilReasonList # {http://www.opengis.net/gml/3.2}booleanOrNilReasonList
from komle.write_bindings._nsgroup import NameOrNilReasonList # {http://www.opengis.net/gml/3.2}NameOrNilReasonList
from komle.write_bindings._nsgroup import doubleOrNilReasonList # {http://www.opengis.net/gml/3.2}doubleOrNilReasonList
from komle.write_bindings._nsgroup import integerOrNilReasonList # {http://www.opengis.net/gml/3.2}integerOrNilReasonList
from komle.write_bindings._nsgroup import MeasureListType # {http://www.opengis.net/gml/3.2}MeasureListType
from komle.write_bindings._nsgroup import CTD_ANON_6 # None
from komle.write_bindings._nsgroup import CoordinateOperationPropertyType # {http://www.opengis.net/gml/3.2}CoordinateOperationPropertyType
from komle.write_bindings._nsgroup import SingleOperationPropertyType # {http://www.opengis.net/gml/3.2}SingleOperationPropertyType
from komle.write_bindings._nsgroup import GeneralConversionPropertyType # {http://www.opengis.net/gml/3.2}GeneralConversionPropertyType
from komle.write_bindings._nsgroup import GeneralTransformationPropertyType # {http://www.opengis.net/gml/3.2}GeneralTransformationPropertyType
from komle.write_bindings._nsgroup import ConcatenatedOperationPropertyType # {http://www.opengis.net/gml/3.2}ConcatenatedOperationPropertyType
from komle.write_bindings._nsgroup import PassThroughOperationPropertyType # {http://www.opengis.net/gml/3.2}PassThroughOperationPropertyType
from komle.write_bindings._nsgroup import ConversionPropertyType # {http://www.opengis.net/gml/3.2}ConversionPropertyType
from komle.write_bindings._nsgroup import TransformationPropertyType # {http://www.opengis.net/gml/3.2}TransformationPropertyType
from komle.write_bindings._nsgroup import CTD_ANON_7 # None
from komle.write_bindings._nsgroup import OperationMethodPropertyType # {http://www.opengis.net/gml/3.2}OperationMethodPropertyType
from komle.write_bindings._nsgroup import AbstractGeneralOperationParameterPropertyType # {http://www.opengis.net/gml/3.2}AbstractGeneralOperationParameterPropertyType
from komle.write_bindings._nsgroup import OperationParameterPropertyType # {http://www.opengis.net/gml/3.2}OperationParameterPropertyType
from komle.write_bindings._nsgroup import OperationParameterGroupPropertyType # {http://www.opengis.net/gml/3.2}OperationParameterGroupPropertyType
from komle.write_bindings._nsgroup import SingleCRSPropertyType # {http://www.opengis.net/gml/3.2}SingleCRSPropertyType
from komle.write_bindings._nsgroup import CompoundCRSPropertyType # {http://www.opengis.net/gml/3.2}CompoundCRSPropertyType
from komle.write_bindings._nsgroup import GeodeticCRSPropertyType # {http://www.opengis.net/gml/3.2}GeodeticCRSPropertyType
from komle.write_bindings._nsgroup import VerticalCRSPropertyType # {http://www.opengis.net/gml/3.2}VerticalCRSPropertyType
from komle.write_bindings._nsgroup import ProjectedCRSPropertyType # {http://www.opengis.net/gml/3.2}ProjectedCRSPropertyType
from komle.write_bindings._nsgroup import DerivedCRSPropertyType # {http://www.opengis.net/gml/3.2}DerivedCRSPropertyType
from komle.write_bindings._nsgroup import EngineeringCRSPropertyType # {http://www.opengis.net/gml/3.2}EngineeringCRSPropertyType
from komle.write_bindings._nsgroup import ImageCRSPropertyType # {http://www.opengis.net/gml/3.2}ImageCRSPropertyType
from komle.write_bindings._nsgroup import TemporalCRSPropertyType # {http://www.opengis.net/gml/3.2}TemporalCRSPropertyType
from komle.write_bindings._nsgroup import CoordinateSystemAxisPropertyType # {http://www.opengis.net/gml/3.2}CoordinateSystemAxisPropertyType
from komle.write_bindings._nsgroup import CoordinateSystemPropertyType # {http://www.opengis.net/gml/3.2}CoordinateSystemPropertyType
from komle.write_bindings._nsgroup import EllipsoidalCSPropertyType # {http://www.opengis.net/gml/3.2}EllipsoidalCSPropertyType
from komle.write_bindings._nsgroup import CartesianCSPropertyType # {http://www.opengis.net/gml/3.2}CartesianCSPropertyType
from komle.write_bindings._nsgroup import VerticalCSPropertyType # {http://www.opengis.net/gml/3.2}VerticalCSPropertyType
from komle.write_bindings._nsgroup import TimeCSPropertyType # {http://www.opengis.net/gml/3.2}TimeCSPropertyType
from komle.write_bindings._nsgroup import LinearCSPropertyType # {http://www.opengis.net/gml/3.2}LinearCSPropertyType
from komle.write_bindings._nsgroup import UserDefinedCSPropertyType # {http://www.opengis.net/gml/3.2}UserDefinedCSPropertyType
from komle.write_bindings._nsgroup import SphericalCSPropertyType # {http://www.opengis.net/gml/3.2}SphericalCSPropertyType
from komle.write_bindings._nsgroup import PolarCSPropertyType # {http://www.opengis.net/gml/3.2}PolarCSPropertyType
from komle.write_bindings._nsgroup import CylindricalCSPropertyType # {http://www.opengis.net/gml/3.2}CylindricalCSPropertyType
from komle.write_bindings._nsgroup import AffineCSPropertyType # {http://www.opengis.net/gml/3.2}AffineCSPropertyType
from komle.write_bindings._nsgroup import AbstractCoverageType # {http://www.opengis.net/gml/3.2}AbstractCoverageType
from komle.write_bindings._nsgroup import DomainSetType # {http://www.opengis.net/gml/3.2}DomainSetType
from komle.write_bindings._nsgroup import SequenceRuleType # {http://www.opengis.net/gml/3.2}SequenceRuleType
from komle.write_bindings._nsgroup import DatumPropertyType # {http://www.opengis.net/gml/3.2}DatumPropertyType
from komle.write_bindings._nsgroup import GeodeticDatumPropertyType # {http://www.opengis.net/gml/3.2}GeodeticDatumPropertyType
from komle.write_bindings._nsgroup import EllipsoidPropertyType # {http://www.opengis.net/gml/3.2}EllipsoidPropertyType
from komle.write_bindings._nsgroup import PrimeMeridianPropertyType # {http://www.opengis.net/gml/3.2}PrimeMeridianPropertyType
from komle.write_bindings._nsgroup import EngineeringDatumPropertyType # {http://www.opengis.net/gml/3.2}EngineeringDatumPropertyType
from komle.write_bindings._nsgroup import ImageDatumPropertyType # {http://www.opengis.net/gml/3.2}ImageDatumPropertyType
from komle.write_bindings._nsgroup import VerticalDatumPropertyType # {http://www.opengis.net/gml/3.2}VerticalDatumPropertyType
from komle.write_bindings._nsgroup import TemporalDatumPropertyType # {http://www.opengis.net/gml/3.2}TemporalDatumPropertyType
from komle.write_bindings._nsgroup import OperationPropertyType # {http://www.opengis.net/gml/3.2}OperationPropertyType
from komle.write_bindings._nsgroup import TemporalCSPropertyType # {http://www.opengis.net/gml/3.2}TemporalCSPropertyType
from komle.write_bindings._nsgroup import ObliqueCartesianCSPropertyType # {http://www.opengis.net/gml/3.2}ObliqueCartesianCSPropertyType
from komle.write_bindings._nsgroup import GeographicCRSPropertyType # {http://www.opengis.net/gml/3.2}GeographicCRSPropertyType
from komle.write_bindings._nsgroup import GeocentricCRSPropertyType # {http://www.opengis.net/gml/3.2}GeocentricCRSPropertyType
from komle.write_bindings._nsgroup import StringOrRefType # {http://www.opengis.net/gml/3.2}StringOrRefType
from komle.write_bindings._nsgroup import MetaDataPropertyType # {http://www.opengis.net/gml/3.2}MetaDataPropertyType
from komle.write_bindings._nsgroup import LocationPropertyType # {http://www.opengis.net/gml/3.2}LocationPropertyType
from komle.write_bindings._nsgroup import BoundedFeatureType # {http://www.opengis.net/gml/3.2}BoundedFeatureType
from komle.write_bindings._nsgroup import AbstractFeatureCollectionType # {http://www.opengis.net/gml/3.2}AbstractFeatureCollectionType
from komle.write_bindings._nsgroup import MovingObjectStatusType # {http://www.opengis.net/gml/3.2}MovingObjectStatusType
from komle.write_bindings._nsgroup import DefinitionType # {http://www.opengis.net/gml/3.2}DefinitionType
from komle.write_bindings._nsgroup import DictionaryEntryType # {http://www.opengis.net/gml/3.2}DictionaryEntryType
from komle.write_bindings._nsgroup import DirectionPropertyType # {http://www.opengis.net/gml/3.2}DirectionPropertyType
from komle.write_bindings._nsgroup import DynamicFeatureType # {http://www.opengis.net/gml/3.2}DynamicFeatureType
from komle.write_bindings._nsgroup import DynamicFeatureMemberType # {http://www.opengis.net/gml/3.2}DynamicFeatureMemberType
from komle.write_bindings._nsgroup import FeaturePropertyType # {http://www.opengis.net/gml/3.2}FeaturePropertyType
from komle.write_bindings._nsgroup import BoundingShapeType # {http://www.opengis.net/gml/3.2}BoundingShapeType
from komle.write_bindings._nsgroup import EnvelopeWithTimePeriodType # {http://www.opengis.net/gml/3.2}EnvelopeWithTimePeriodType
from komle.write_bindings._nsgroup import AbstractGeometricAggregateType # {http://www.opengis.net/gml/3.2}AbstractGeometricAggregateType
from komle.write_bindings._nsgroup import MultiGeometryPropertyType # {http://www.opengis.net/gml/3.2}MultiGeometryPropertyType
from komle.write_bindings._nsgroup import MultiPointPropertyType # {http://www.opengis.net/gml/3.2}MultiPointPropertyType
from komle.write_bindings._nsgroup import MultiCurvePropertyType # {http://www.opengis.net/gml/3.2}MultiCurvePropertyType
from komle.write_bindings._nsgroup import MultiSurfacePropertyType # {http://www.opengis.net/gml/3.2}MultiSurfacePropertyType
from komle.write_bindings._nsgroup import MultiSolidPropertyType # {http://www.opengis.net/gml/3.2}MultiSolidPropertyType
from komle.write_bindings._nsgroup import GeometryPropertyType # {http://www.opengis.net/gml/3.2}GeometryPropertyType
from komle.write_bindings._nsgroup import VectorType # {http://www.opengis.net/gml/3.2}VectorType
from komle.write_bindings._nsgroup import AbstractGeometricPrimitiveType # {http://www.opengis.net/gml/3.2}AbstractGeometricPrimitiveType
from komle.write_bindings._nsgroup import GeometricPrimitivePropertyType # {http://www.opengis.net/gml/3.2}GeometricPrimitivePropertyType
from komle.write_bindings._nsgroup import PointPropertyType # {http://www.opengis.net/gml/3.2}PointPropertyType
from komle.write_bindings._nsgroup import CurvePropertyType # {http://www.opengis.net/gml/3.2}CurvePropertyType
from komle.write_bindings._nsgroup import SurfacePropertyType # {http://www.opengis.net/gml/3.2}SurfacePropertyType
from komle.write_bindings._nsgroup import GeometricComplexType # {http://www.opengis.net/gml/3.2}GeometricComplexType
from komle.write_bindings._nsgroup import GeometricComplexPropertyType # {http://www.opengis.net/gml/3.2}GeometricComplexPropertyType
from komle.write_bindings._nsgroup import ArcType # {http://www.opengis.net/gml/3.2}ArcType
from komle.write_bindings._nsgroup import ArcByBulgeType # {http://www.opengis.net/gml/3.2}ArcByBulgeType
from komle.write_bindings._nsgroup import CircleByCenterPointType # {http://www.opengis.net/gml/3.2}CircleByCenterPointType
from komle.write_bindings._nsgroup import BezierType # {http://www.opengis.net/gml/3.2}BezierType
from komle.write_bindings._nsgroup import GeodesicType # {http://www.opengis.net/gml/3.2}GeodesicType
from komle.write_bindings._nsgroup import AbstractGriddedSurfaceType # {http://www.opengis.net/gml/3.2}AbstractGriddedSurfaceType
from komle.write_bindings._nsgroup import SolidPropertyType # {http://www.opengis.net/gml/3.2}SolidPropertyType
from komle.write_bindings._nsgroup import AssociationRoleType # {http://www.opengis.net/gml/3.2}AssociationRoleType
from komle.write_bindings._nsgroup import ReferenceType # {http://www.opengis.net/gml/3.2}ReferenceType
from komle.write_bindings._nsgroup import GridType # {http://www.opengis.net/gml/3.2}GridType
from komle.write_bindings._nsgroup import ObservationType # {http://www.opengis.net/gml/3.2}ObservationType
from komle.write_bindings._nsgroup import ProcedurePropertyType # {http://www.opengis.net/gml/3.2}ProcedurePropertyType
from komle.write_bindings._nsgroup import TargetPropertyType # {http://www.opengis.net/gml/3.2}TargetPropertyType
from komle.write_bindings._nsgroup import ResultType # {http://www.opengis.net/gml/3.2}ResultType
from komle.write_bindings._nsgroup import CTD_ANON_8 # None
from komle.write_bindings._nsgroup import CRSPropertyType # {http://www.opengis.net/gml/3.2}CRSPropertyType
from komle.write_bindings._nsgroup import AbstractTimePrimitiveType # {http://www.opengis.net/gml/3.2}AbstractTimePrimitiveType
from komle.write_bindings._nsgroup import TimePrimitivePropertyType # {http://www.opengis.net/gml/3.2}TimePrimitivePropertyType
from komle.write_bindings._nsgroup import AbstractTimeComplexType # {http://www.opengis.net/gml/3.2}AbstractTimeComplexType
from komle.write_bindings._nsgroup import TimeInstantPropertyType # {http://www.opengis.net/gml/3.2}TimeInstantPropertyType
from komle.write_bindings._nsgroup import TimePeriodPropertyType # {http://www.opengis.net/gml/3.2}TimePeriodPropertyType
from komle.write_bindings._nsgroup import TimeIntervalLengthType # {http://www.opengis.net/gml/3.2}TimeIntervalLengthType
from komle.write_bindings._nsgroup import TimeCalendarPropertyType # {http://www.opengis.net/gml/3.2}TimeCalendarPropertyType
from komle.write_bindings._nsgroup import TimeCalendarEraPropertyType # {http://www.opengis.net/gml/3.2}TimeCalendarEraPropertyType
from komle.write_bindings._nsgroup import TimeClockPropertyType # {http://www.opengis.net/gml/3.2}TimeClockPropertyType
from komle.write_bindings._nsgroup import TimeOrdinalEraPropertyType # {http://www.opengis.net/gml/3.2}TimeOrdinalEraPropertyType
from komle.write_bindings._nsgroup import TimeTopologyPrimitivePropertyType # {http://www.opengis.net/gml/3.2}TimeTopologyPrimitivePropertyType
from komle.write_bindings._nsgroup import TimeTopologyComplexPropertyType # {http://www.opengis.net/gml/3.2}TimeTopologyComplexPropertyType
from komle.write_bindings._nsgroup import TimeNodePropertyType # {http://www.opengis.net/gml/3.2}TimeNodePropertyType
from komle.write_bindings._nsgroup import TimeEdgePropertyType # {http://www.opengis.net/gml/3.2}TimeEdgePropertyType
from komle.write_bindings._nsgroup import AbstractTopoPrimitiveType # {http://www.opengis.net/gml/3.2}AbstractTopoPrimitiveType
from komle.write_bindings._nsgroup import NodeOrEdgePropertyType # {http://www.opengis.net/gml/3.2}NodeOrEdgePropertyType
from komle.write_bindings._nsgroup import NodePropertyType # {http://www.opengis.net/gml/3.2}NodePropertyType
from komle.write_bindings._nsgroup import FaceOrTopoSolidPropertyType # {http://www.opengis.net/gml/3.2}FaceOrTopoSolidPropertyType
from komle.write_bindings._nsgroup import TopoSolidPropertyType # {http://www.opengis.net/gml/3.2}TopoSolidPropertyType
from komle.write_bindings._nsgroup import DirectedNodePropertyType # {http://www.opengis.net/gml/3.2}DirectedNodePropertyType
from komle.write_bindings._nsgroup import DirectedEdgePropertyType # {http://www.opengis.net/gml/3.2}DirectedEdgePropertyType
from komle.write_bindings._nsgroup import DirectedFacePropertyType # {http://www.opengis.net/gml/3.2}DirectedFacePropertyType
from komle.write_bindings._nsgroup import DirectedTopoSolidPropertyType # {http://www.opengis.net/gml/3.2}DirectedTopoSolidPropertyType
from komle.write_bindings._nsgroup import TopoPointType # {http://www.opengis.net/gml/3.2}TopoPointType
from komle.write_bindings._nsgroup import TopoCurveType # {http://www.opengis.net/gml/3.2}TopoCurveType
from komle.write_bindings._nsgroup import TopoSurfaceType # {http://www.opengis.net/gml/3.2}TopoSurfaceType
from komle.write_bindings._nsgroup import TopoVolumeType # {http://www.opengis.net/gml/3.2}TopoVolumeType
from komle.write_bindings._nsgroup import TopoComplexType # {http://www.opengis.net/gml/3.2}TopoComplexType
from komle.write_bindings._nsgroup import TopoPrimitiveMemberType # {http://www.opengis.net/gml/3.2}TopoPrimitiveMemberType
from komle.write_bindings._nsgroup import TopoComplexPropertyType # {http://www.opengis.net/gml/3.2}TopoComplexPropertyType
from komle.write_bindings._nsgroup import UnitOfMeasureType # {http://www.opengis.net/gml/3.2}UnitOfMeasureType
from komle.write_bindings._nsgroup import CTD_ANON_9 # None
from komle.write_bindings._nsgroup import CTD_ANON_10 # None
from komle.write_bindings._nsgroup import CTD_ANON_11 # None
from komle.write_bindings._nsgroup import ValuePropertyType # {http://www.opengis.net/gml/3.2}ValuePropertyType
from komle.write_bindings._nsgroup import ValueArrayType # {http://www.opengis.net/gml/3.2}ValueArrayType
from komle.write_bindings._nsgroup import BooleanPropertyType # {http://www.opengis.net/gml/3.2}BooleanPropertyType
from komle.write_bindings._nsgroup import CategoryPropertyType # {http://www.opengis.net/gml/3.2}CategoryPropertyType
from komle.write_bindings._nsgroup import QuantityPropertyType # {http://www.opengis.net/gml/3.2}QuantityPropertyType
from komle.write_bindings._nsgroup import CountPropertyType # {http://www.opengis.net/gml/3.2}CountPropertyType
from komle.write_bindings._nsgroup import CodeOrNilReasonListType # {http://www.opengis.net/gml/3.2}CodeOrNilReasonListType
from komle.write_bindings._nsgroup import MeasureOrNilReasonListType # {http://www.opengis.net/gml/3.2}MeasureOrNilReasonListType
from komle.write_bindings._nsgroup import DiscreteCoverageType # {http://www.opengis.net/gml/3.2}DiscreteCoverageType
from komle.write_bindings._nsgroup import AbstractContinuousCoverageType # {http://www.opengis.net/gml/3.2}AbstractContinuousCoverageType
from komle.write_bindings._nsgroup import PriorityLocationPropertyType # {http://www.opengis.net/gml/3.2}PriorityLocationPropertyType
from komle.write_bindings._nsgroup import FeatureCollectionType # {http://www.opengis.net/gml/3.2}FeatureCollectionType
from komle.write_bindings._nsgroup import DefinitionProxyType # {http://www.opengis.net/gml/3.2}DefinitionProxyType
from komle.write_bindings._nsgroup import DictionaryType # {http://www.opengis.net/gml/3.2}DictionaryType
from komle.write_bindings._nsgroup import DynamicFeatureCollectionType # {http://www.opengis.net/gml/3.2}DynamicFeatureCollectionType
from komle.write_bindings._nsgroup import MultiGeometryType # {http://www.opengis.net/gml/3.2}MultiGeometryType
from komle.write_bindings._nsgroup import MultiPointType # {http://www.opengis.net/gml/3.2}MultiPointType
from komle.write_bindings._nsgroup import MultiCurveType # {http://www.opengis.net/gml/3.2}MultiCurveType
from komle.write_bindings._nsgroup import MultiSurfaceType # {http://www.opengis.net/gml/3.2}MultiSurfaceType
from komle.write_bindings._nsgroup import MultiSolidType # {http://www.opengis.net/gml/3.2}MultiSolidType
from komle.write_bindings._nsgroup import PointType # {http://www.opengis.net/gml/3.2}PointType
from komle.write_bindings._nsgroup import AbstractCurveType # {http://www.opengis.net/gml/3.2}AbstractCurveType
from komle.write_bindings._nsgroup import AbstractSurfaceType # {http://www.opengis.net/gml/3.2}AbstractSurfaceType
from komle.write_bindings._nsgroup import CircleType # {http://www.opengis.net/gml/3.2}CircleType
from komle.write_bindings._nsgroup import ConeType # {http://www.opengis.net/gml/3.2}ConeType
from komle.write_bindings._nsgroup import CylinderType # {http://www.opengis.net/gml/3.2}CylinderType
from komle.write_bindings._nsgroup import SphereType # {http://www.opengis.net/gml/3.2}SphereType
from komle.write_bindings._nsgroup import AbstractSolidType # {http://www.opengis.net/gml/3.2}AbstractSolidType
from komle.write_bindings._nsgroup import RectifiedGridType # {http://www.opengis.net/gml/3.2}RectifiedGridType
from komle.write_bindings._nsgroup import LengthType # {http://www.opengis.net/gml/3.2}LengthType
from komle.write_bindings._nsgroup import ScaleType # {http://www.opengis.net/gml/3.2}ScaleType
from komle.write_bindings._nsgroup import TimeType # {http://www.opengis.net/gml/3.2}TimeType
from komle.write_bindings._nsgroup import GridLengthType # {http://www.opengis.net/gml/3.2}GridLengthType
from komle.write_bindings._nsgroup import AreaType # {http://www.opengis.net/gml/3.2}AreaType
from komle.write_bindings._nsgroup import VolumeType # {http://www.opengis.net/gml/3.2}VolumeType
from komle.write_bindings._nsgroup import SpeedType # {http://www.opengis.net/gml/3.2}SpeedType
from komle.write_bindings._nsgroup import AngleType # {http://www.opengis.net/gml/3.2}AngleType
from komle.write_bindings._nsgroup import DirectedObservationType # {http://www.opengis.net/gml/3.2}DirectedObservationType
from komle.write_bindings._nsgroup import IdentifiedObjectType # {http://www.opengis.net/gml/3.2}IdentifiedObjectType
from komle.write_bindings._nsgroup import RelatedTimeType # {http://www.opengis.net/gml/3.2}RelatedTimeType
from komle.write_bindings._nsgroup import AbstractTimeGeometricPrimitiveType # {http://www.opengis.net/gml/3.2}AbstractTimeGeometricPrimitiveType
from komle.write_bindings._nsgroup import TimeReferenceSystemType # {http://www.opengis.net/gml/3.2}TimeReferenceSystemType
from komle.write_bindings._nsgroup import TimeCalendarEraType # {http://www.opengis.net/gml/3.2}TimeCalendarEraType
from komle.write_bindings._nsgroup import TimeOrdinalEraType # {http://www.opengis.net/gml/3.2}TimeOrdinalEraType
from komle.write_bindings._nsgroup import AbstractTimeTopologyPrimitiveType # {http://www.opengis.net/gml/3.2}AbstractTimeTopologyPrimitiveType
from komle.write_bindings._nsgroup import TimeTopologyComplexType # {http://www.opengis.net/gml/3.2}TimeTopologyComplexType
from komle.write_bindings._nsgroup import NodeType # {http://www.opengis.net/gml/3.2}NodeType
from komle.write_bindings._nsgroup import EdgeType # {http://www.opengis.net/gml/3.2}EdgeType
from komle.write_bindings._nsgroup import FaceType # {http://www.opengis.net/gml/3.2}FaceType
from komle.write_bindings._nsgroup import TopoSolidType # {http://www.opengis.net/gml/3.2}TopoSolidType
from komle.write_bindings._nsgroup import UnitDefinitionType # {http://www.opengis.net/gml/3.2}UnitDefinitionType
from komle.write_bindings._nsgroup import DerivationUnitTermType # {http://www.opengis.net/gml/3.2}DerivationUnitTermType
from komle.write_bindings._nsgroup import ConversionToPreferredUnitType # {http://www.opengis.net/gml/3.2}ConversionToPreferredUnitType
from komle.write_bindings._nsgroup import CTD_ANON_12 # None
from komle.write_bindings._nsgroup import STD_ANON_8 # None
from komle.write_bindings._nsgroup import CountExtentType # {http://www.opengis.net/gml/3.2}CountExtentType
from komle.write_bindings._nsgroup import STD_ANON_9 # None
from komle.write_bindings._nsgroup import AbstractCoordinateOperationType # {http://www.opengis.net/gml/3.2}AbstractCoordinateOperationType
from komle.write_bindings._nsgroup import OperationMethodType # {http://www.opengis.net/gml/3.2}OperationMethodType
from komle.write_bindings._nsgroup import AbstractGeneralOperationParameterType # {http://www.opengis.net/gml/3.2}AbstractGeneralOperationParameterType
from komle.write_bindings._nsgroup import CoordinateSystemAxisType # {http://www.opengis.net/gml/3.2}CoordinateSystemAxisType
from komle.write_bindings._nsgroup import AbstractCoordinateSystemType # {http://www.opengis.net/gml/3.2}AbstractCoordinateSystemType
from komle.write_bindings._nsgroup import AbstractDatumType # {http://www.opengis.net/gml/3.2}AbstractDatumType
from komle.write_bindings._nsgroup import EllipsoidType # {http://www.opengis.net/gml/3.2}EllipsoidType
from komle.write_bindings._nsgroup import PrimeMeridianType # {http://www.opengis.net/gml/3.2}PrimeMeridianType
from komle.write_bindings._nsgroup import LineStringType # {http://www.opengis.net/gml/3.2}LineStringType
from komle.write_bindings._nsgroup import PolygonType # {http://www.opengis.net/gml/3.2}PolygonType
from komle.write_bindings._nsgroup import AbstractRingType # {http://www.opengis.net/gml/3.2}AbstractRingType
from komle.write_bindings._nsgroup import CompositeCurveType # {http://www.opengis.net/gml/3.2}CompositeCurveType
from komle.write_bindings._nsgroup import CompositeSurfaceType # {http://www.opengis.net/gml/3.2}CompositeSurfaceType
from komle.write_bindings._nsgroup import CompositeSolidType # {http://www.opengis.net/gml/3.2}CompositeSolidType
from komle.write_bindings._nsgroup import CurveType # {http://www.opengis.net/gml/3.2}CurveType
from komle.write_bindings._nsgroup import OrientableCurveType # {http://www.opengis.net/gml/3.2}OrientableCurveType
from komle.write_bindings._nsgroup import SurfaceType # {http://www.opengis.net/gml/3.2}SurfaceType
from komle.write_bindings._nsgroup import OrientableSurfaceType # {http://www.opengis.net/gml/3.2}OrientableSurfaceType
from komle.write_bindings._nsgroup import SolidType # {http://www.opengis.net/gml/3.2}SolidType
from komle.write_bindings._nsgroup import ShellType # {http://www.opengis.net/gml/3.2}ShellType
from komle.write_bindings._nsgroup import DirectedObservationAtDistanceType # {http://www.opengis.net/gml/3.2}DirectedObservationAtDistanceType
from komle.write_bindings._nsgroup import AbstractCRSType # {http://www.opengis.net/gml/3.2}AbstractCRSType
from komle.write_bindings._nsgroup import TimeInstantType # {http://www.opengis.net/gml/3.2}TimeInstantType
from komle.write_bindings._nsgroup import TimePeriodType # {http://www.opengis.net/gml/3.2}TimePeriodType
from komle.write_bindings._nsgroup import TimeCoordinateSystemType # {http://www.opengis.net/gml/3.2}TimeCoordinateSystemType
from komle.write_bindings._nsgroup import TimeCalendarType # {http://www.opengis.net/gml/3.2}TimeCalendarType
from komle.write_bindings._nsgroup import TimeClockType # {http://www.opengis.net/gml/3.2}TimeClockType
from komle.write_bindings._nsgroup import TimeOrdinalReferenceSystemType # {http://www.opengis.net/gml/3.2}TimeOrdinalReferenceSystemType
from komle.write_bindings._nsgroup import TimeNodeType # {http://www.opengis.net/gml/3.2}TimeNodeType
from komle.write_bindings._nsgroup import TimeEdgeType # {http://www.opengis.net/gml/3.2}TimeEdgeType
from komle.write_bindings._nsgroup import BaseUnitType # {http://www.opengis.net/gml/3.2}BaseUnitType
from komle.write_bindings._nsgroup import DerivedUnitType # {http://www.opengis.net/gml/3.2}DerivedUnitType
from komle.write_bindings._nsgroup import ConventionalUnitType # {http://www.opengis.net/gml/3.2}ConventionalUnitType
from komle.write_bindings._nsgroup import CategoryExtentType # {http://www.opengis.net/gml/3.2}CategoryExtentType
from komle.write_bindings._nsgroup import QuantityExtentType # {http://www.opengis.net/gml/3.2}QuantityExtentType
from komle.write_bindings._nsgroup import AbstractGeneralConversionType # {http://www.opengis.net/gml/3.2}AbstractGeneralConversionType
from komle.write_bindings._nsgroup import AbstractGeneralTransformationType # {http://www.opengis.net/gml/3.2}AbstractGeneralTransformationType
from komle.write_bindings._nsgroup import ConcatenatedOperationType # {http://www.opengis.net/gml/3.2}ConcatenatedOperationType
from komle.write_bindings._nsgroup import PassThroughOperationType # {http://www.opengis.net/gml/3.2}PassThroughOperationType
from komle.write_bindings._nsgroup import OperationParameterType # {http://www.opengis.net/gml/3.2}OperationParameterType
from komle.write_bindings._nsgroup import OperationParameterGroupType # {http://www.opengis.net/gml/3.2}OperationParameterGroupType
from komle.write_bindings._nsgroup import AbstractGeneralDerivedCRSType # {http://www.opengis.net/gml/3.2}AbstractGeneralDerivedCRSType
from komle.write_bindings._nsgroup import CompoundCRSType # {http://www.opengis.net/gml/3.2}CompoundCRSType
from komle.write_bindings._nsgroup import GeodeticCRSType # {http://www.opengis.net/gml/3.2}GeodeticCRSType
from komle.write_bindings._nsgroup import VerticalCRSType # {http://www.opengis.net/gml/3.2}VerticalCRSType
from komle.write_bindings._nsgroup import EngineeringCRSType # {http://www.opengis.net/gml/3.2}EngineeringCRSType
from komle.write_bindings._nsgroup import ImageCRSType # {http://www.opengis.net/gml/3.2}ImageCRSType
from komle.write_bindings._nsgroup import TemporalCRSType # {http://www.opengis.net/gml/3.2}TemporalCRSType
from komle.write_bindings._nsgroup import EllipsoidalCSType # {http://www.opengis.net/gml/3.2}EllipsoidalCSType
from komle.write_bindings._nsgroup import CartesianCSType # {http://www.opengis.net/gml/3.2}CartesianCSType
from komle.write_bindings._nsgroup import VerticalCSType # {http://www.opengis.net/gml/3.2}VerticalCSType
from komle.write_bindings._nsgroup import TimeCSType # {http://www.opengis.net/gml/3.2}TimeCSType
from komle.write_bindings._nsgroup import LinearCSType # {http://www.opengis.net/gml/3.2}LinearCSType
from komle.write_bindings._nsgroup import UserDefinedCSType # {http://www.opengis.net/gml/3.2}UserDefinedCSType
from komle.write_bindings._nsgroup import SphericalCSType # {http://www.opengis.net/gml/3.2}SphericalCSType
from komle.write_bindings._nsgroup import PolarCSType # {http://www.opengis.net/gml/3.2}PolarCSType
from komle.write_bindings._nsgroup import CylindricalCSType # {http://www.opengis.net/gml/3.2}CylindricalCSType
from komle.write_bindings._nsgroup import AffineCSType # {http://www.opengis.net/gml/3.2}AffineCSType
from komle.write_bindings._nsgroup import GeodeticDatumType # {http://www.opengis.net/gml/3.2}GeodeticDatumType
from komle.write_bindings._nsgroup import EngineeringDatumType # {http://www.opengis.net/gml/3.2}EngineeringDatumType
from komle.write_bindings._nsgroup import ImageDatumType # {http://www.opengis.net/gml/3.2}ImageDatumType
from komle.write_bindings._nsgroup import VerticalDatumType # {http://www.opengis.net/gml/3.2}VerticalDatumType
from komle.write_bindings._nsgroup import TemporalDatumBaseType # {http://www.opengis.net/gml/3.2}TemporalDatumBaseType
from komle.write_bindings._nsgroup import TemporalCSType # {http://www.opengis.net/gml/3.2}TemporalCSType
from komle.write_bindings._nsgroup import ObliqueCartesianCSType # {http://www.opengis.net/gml/3.2}ObliqueCartesianCSType
from komle.write_bindings._nsgroup import GeographicCRSType # {http://www.opengis.net/gml/3.2}GeographicCRSType
from komle.write_bindings._nsgroup import GeocentricCRSType # {http://www.opengis.net/gml/3.2}GeocentricCRSType
from komle.write_bindings._nsgroup import LinearRingType # {http://www.opengis.net/gml/3.2}LinearRingType
from komle.write_bindings._nsgroup import RingType # {http://www.opengis.net/gml/3.2}RingType
from komle.write_bindings._nsgroup import TinType # {http://www.opengis.net/gml/3.2}TinType
from komle.write_bindings._nsgroup import ConversionType # {http://www.opengis.net/gml/3.2}ConversionType
from komle.write_bindings._nsgroup import TransformationType # {http://www.opengis.net/gml/3.2}TransformationType
from komle.write_bindings._nsgroup import ProjectedCRSType # {http://www.opengis.net/gml/3.2}ProjectedCRSType
from komle.write_bindings._nsgroup import DerivedCRSType # {http://www.opengis.net/gml/3.2}DerivedCRSType
from komle.write_bindings._nsgroup import TemporalDatumType # {http://www.opengis.net/gml/3.2}TemporalDatumType
